### ISSUE TITLE
SNOW-940605: In the latest release v3.3.0, `ImportError` caused by `arrow_iterator` if cython extension can not be compiled

### ISSUE THREAD

**Issue by philiptzou** [snowflakedb/snowflake-connector-python#1768] opened 2023-10-13 15:02 UTC
After upgraded to 3.3.0, I noticed the `ImportError` caused by importing `arrow_iterator` in my code. And I found it was caused by this line:

https://github.com/snowflakedb/snowflake-connector-python/blob/4e29385a7103def391dca22b38d11679626c253a/src/snowflake/connector/result_batch.py#L17

Since compiling `snowflake.connector.arrow_iterator` is [optional](https://github.com/snowflakedb/snowflake-connector-python/blob/1d87730162ef55fbf49407f5875102ec93b1b91e/setup.py#L45C1-L67), it seems to me that the importing of `arrow_iterator` should be always enclosed by try-except clause, like what has been done in [`cursor.py`](https://github.com/snowflakedb/snowflake-connector-python/blob/1d87730162ef55fbf49407f5875102ec93b1b91e/src/snowflake/connector/cursor.py#L89C1-L97) file.

**Comment by sfc-gh-aling** [comment] 2023-10-13 15:23
hey @philiptzou , thanks for catching this, we will do a patch release shortly for this

**Comment by sfc-gh-aling** [comment] 2023-10-13 15:31
I have a PR for the fix: https://github.com/snowflakedb/snowflake-connector-python/pull/1769

**Comment by sfc-gh-aling** [comment] 2023-10-13 21:52
for future folks who encounter the same issue, we've identified the root cause of the import error is caused by cython extension not being compiled.

we have already merged the fix: https://github.com/snowflakedb/snowflake-connector-python/pull/1769 that will not import arrow iterator if cython extension is not compiled and will do a patch release on Monday (Oct 16).

as a short term workaround, please use snowflake-connector-python v3.2.1 if you are going to install connector from source code and can not compile the cython extensions in your local environment:
`pip install snowflake-connector-python==3.2.1`

thanks for your understanding!

**Comment by philiptzou** [comment] 2023-10-13 22:14
> hey @philiptzou , thanks for catching this, we will do a patch release shortly for this. can you use the v3.2.* version at the moment?

Already did so. Thanks for the quick response!

**Comment by sfc-gh-aling** [comment] 2023-10-17 22:03
hi @philiptzou sorry about the delay of the release, we are encountering some infra issue which blocks our release and works on fixing them asap

**Comment by philiptzou** [comment] 2023-10-18 17:21
@sfc-gh-aling No worries. A little bit about my use case:

I didn't installed the library from source code. However, I deliberately deleted the unused `arrow_iterator` after installing, since it can save up ~100MB in my release package to AWS Lambda. Lambda has an unzipped package size limit of 250MB if without using Docker image.

I'm just wondering if you have plan to make a "slim" version release in the future? It will be very helpful for the similar use cases like mine.

**Comment by sfc-gh-aling** [comment] 2023-10-18 22:49
hi @philiptzou , we have released v3.3.1 which fixed the import issue.

regarding the "slim" version, YES, we're working on adopting a new project called apache-nanoarrow which will help reduce the package size down to ~5MB.

v3.3.0 is already using the apache-nanoarrow project as default arrow data converter, but we still keeps the old arrow libraries as we want to provide a way to switch back to the old approach in case we find issue.

If things move well, we will release newer version of connector by the end of this month which completely get rid of vendored arrow binaries, reducing the size to ~5MB, as well as no longer pinning the pyarrow dependency.

**Closed by sfc-gh-aling** 2023-10-18 22:49 UTC
Labels: bug
