### ISSUE TITLE
Support for cryptography > 1.8?

### ISSUE THREAD

**Issue by tbeuthel** [snowflakedb/snowflake-connector-python#32] opened 2017-08-11 18:47 UTC
Is there a reason why the library depends on cryptography < 1.8? I'm having problems installing an earlier version of cryptography with new versions of openssl, and therefore can't install this library.

**Comment by smtakeda** [comment] 2017-08-11 21:30
I had concern about the change in `cryptography` 1.8 that started using `asn1crypto` instead of `pyasn1`, since Python connector also leverages `pyasn1` for OCSP checks and in theory, it should not but I was worried mixing them could cause issues, so I've added version dependency for safety.

Recently I ran a couple of tests with cryptography 2.0.x, so far no issue was found. I'll revisit and if no issue there again, I'll change the version range to `1.7>=,<2.1`.

**Comment by smtakeda** [comment] 2017-08-11 22:39
PyOpenSSL version range should be updated too, i.e., `>=16.2.0,<18.0.0`

**Comment by tbeuthel** [comment] 2017-08-11 22:44
Awesome, thanks! In the meantime I worked around it by installing libssl1.0-dev for my purposes

**Comment by smtakeda** [comment] 2017-08-11 23:04
Came across this error when upgrading cryptography. ```  File "/home/somebody/conftest.py", line 30, in <module>
    import snowflake.connector
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/snowflake/connector/connection.py", line 14, in <module>
    from . import network
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/snowflake/connector/network.py", line 19, in <module>
    import OpenSSL
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/somewhere/Python/pvenv_3.4/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 84, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCT'
```
The workaround is:
* Uninstall `cryptography` by running `pip uninstall cryptography`
* Delete the directory `.../site-packages/cryptography/` manually
* Reinstall `snowflake-connector-python`

Looks like the directory structure of `cryptography` changed since 1.7.2.

I recall I hit this error before and gave up changing `cryptography` package a while back.

**Comment by smtakeda** [comment] 2017-08-15 22:48
The above incident is not reproducible. I hit a couple of times total but cannot identify a reproducible case...

**Comment by smtakeda** [comment] 2017-08-15 23:33
Committed the change:
https://github.com/snowflakedb/snowflake-connector-python/commit/c59da660607d6b84cc6aac7847adc1308eef6068

**Closed by smtakeda** 2017-08-15 23:33 UTC
Labels: enhancement
