### ISSUE TITLE
SNOW-336834: cursor.fetch_pandas_all() is unable to pull data from snowflake. If the records are around 1 million

### ISSUE THREAD

**Issue by amiteshQA** [snowflakedb/snowflake-connector-python#674] opened 2021-04-09 18:56 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
python version =3.6
2. What operating system and processor architecture are you using?
Windows-10-10.0.19041-SP0
3. What are the component versions in the environment (`pip freeze`)?

```
snowflake==0.0.3
snowflake-connector-python==2.3.9
pandas==1.1.5
pyarrow==0.17.1
numpy==1.19.5
```

4. What did you do?
```
class ExportToCsv:
    _cursor = None

    def __init__(self, account, user, password, role, warehouse):

        connection = sfc.connect(
            account=account,
            user=user,
            password=password,
            role=role,
            warehouse=warehouse
        )
        print("Connecting to snowflake.....")
        self._cursor = connection.cursor()

    def export_to_csv(self, query, path_to_csv):
        try:
            query = "{}".format(query)
            
            self._cursor.execute(query)

            df = self._cursor.fetch_pandas_all()

            path_to_csv = "{}".format(path_to_csv)

            df.to_csv(path_to_csv, index=False)
        finally:
            self._cursor.close()
```
5. What did you expect to see?
I was expecting it to fetch 2,00,000 records from snowflake and create a dataframe of that.

6. What did you see instead?
File "D:\Cloud\call_test.py", line 20, in <module>
    snowflakeConnect.export_to_csv(query, path_to_csv)
  File "D:\Cloud\snowflake_to_dataframe.py", line 28, in export_to_csv
    df = self._cursor.fetch_pandas_all()
  File "C:\AMi-space\airflow\venv\lib\site-packages\snowflake\connector\cursor.py", line 855, in fetch_pandas_all
    return self._result._fetch_pandas_all(**kwargs)
  File "src\snowflake\connector\arrow_result.pyx", line 259, in snowflake.connector.arrow_result.ArrowResult._fetch_pandas_all
  File "pyarrow\array.pxi", line 751, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\table.pxi", line 1668, in pyarrow.lib.Table._to_pandas
  File "C:\AMi-space\airflow\venv\lib\site-packages\pyarrow\pandas_compat.py", line 792, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "C:\AMi-space\airflow\venv\lib\site-packages\pyarrow\pandas_compat.py", line 1131, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow\table.pxi", line 1117, in pyarrow.lib.table_to_blocks
  File "pyarrow\error.pxi", line 116, in pyarrow.lib.check_status
pyarrow.lib.ArrowException: Unknown error: Wrapping FEBRAMAT Federa��o Brasileira De Redes failed

**Comment by sfc-gh-jbahk** [comment] 2022-01-13 23:47
Hi @amiteshQA, I'm trying to reproduce this but am unable to do so. Do you have an associated query ID? Has this been resolved?

**Comment by sfc-gh-jbahk** [comment] 2022-01-20 20:48
Closing this for now as I'm unable to reproduce - please file a support ticket with diagnostic information like the query ID, especially if it's intermittent. Thank you.

**Closed by sfc-gh-jbahk** 2022-01-20 20:48 UTC
