### ISSUE TITLE
SNOW-1367711: Log Error coming from line CArrowTableIterator.cpp#L230 making a lot noise

### ISSUE THREAD

**Issue by rajathpatel23** [snowflakedb/snowflake-connector-python#1941] opened 2024-05-06 15:15 UTC
### Python version

python 3.10.7

### Operating system and processor architecture

Linux

### Installed packages

```python
snowflake-connector-python==3.10.0
pandas==2.2.2
```

### What did you do?

```python
We were trying to fetch data from Snowflake in bulk using `fetch_pandas_all.`
```

### What did you expect to see?

We are getting this log error while processing data from Snowflake. It seems to be making a lot of noise; I would like to understand - what was the change made in the [snowflake ticket](https://snowflakecomputing.atlassian.net/browse/SNOW-1269820)? I feel the [logger there](https://github.com/snowflakedb/snowflake-connector-python/blob/8cdca67faf3fa2a6d31a545d78326b76c31c4c64/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowTableIterator.cpp#L230) is more of debug logger than actual log error.

The changes introduced in this [PR](https://github.com/snowflakedb/snowflake-connector-python/pull/1907/files) seem to be start to give us the log error 

Could you help me with this? Also, can you provide more info on the support for pandas that have come with this change?

### Can you set logging to DEBUG and collect the logs?

```bash
2024-05-01T08:51:05.782-07:00E0501 15:51:04.878359 140214890649152 CArrowTableIterator.cpp:230] scale: 9
```

**Comment by sfc-gh-dszmolka** [comment] 2024-05-06 16:02
looks like duplicate of https://github.com/snowflakedb/snowflake-connector-python/issues/1939 ?

**Closed by sfc-gh-dszmolka** 2024-05-06 16:02 UTC
Labels: bug, needs triage
