### ISSUE TITLE
Pass down ssl_context to `urllib3.util.ssl_wrap_socket`

### ISSUE THREAD

**Issue by adimascio** [snowflakedb/snowflake-connector-python#238] opened 2019-11-19 10:49 UTC
Hi,

Thanks for your work on the snowflake connector! 

I have an issue with SSL handshake that I'll try to describe below.

1. What version of Python are you using (`python --version`)?

`3.6.8`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Linux-4.16.0-1-amd64-x86_64-with-debian-bullseye-sid`

3. What are the component versions in the environment (`pip list`)? 

```$ pip list | grep -i -E 'ssl|urllib|cert|snow'                                                                                         11:18:09
certifi                    2019.9.11 
pyOpenSSL                  19.1.0    
snowflake-connector-python 2.0.4     
urllib3                    1.24.3    
```

4. What did you do?

```python
import urllib3
import snowflake.connector  # ← comment this line and everything is fine


def get(url):
    pool_manager = urllib3.PoolManager()
    res = pool_manager.request('GET', url)
    return res.status


assert get('https://wikipedia.org') == 200
```

5. What did you expect to see?

I expect not to see any error.

6. What did you see instead?

```
Traceback (most recent call last):
  File "/home/adim/debug-run/snowrror.py", line 11, in <module>
    assert get('https://wikipedia.org') == 200
  File "/home/adim/debug-run/snowrror.py", line 7, in get
    res = pool_manager.request('GET', url)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/adim/.virtualenvs/peakina/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wikipedia.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

As far as I can, tell, the problem lies in the monkeypatch of `ssl_wrap_socket` with `ssl_wrap_socket_with_ocsp`  (cf. https://github.com/snowflakedb/snowflake-connector-python/blob/master/ssl_wrap_socket.py#L374 ). `ssl_context` is not passed down to the original function which causes the error. 

The error doesn't occur if `urllib3.PoolManager` is instantiated with `cert_reqs='CERT_REQUIRED', ca_certs=certifi.where()`.

**Comment by keller00** [comment] 2019-11-19 18:24
I investigated this when updating to the newest `urllib3` version.
This is necessary because `botocore` uses a non `PyOpenSSLContext` context. So passing the given one would create regressions. However; our default context options might need to be adjusted.
I'm going to investigate.

**Comment by keller00** [comment] 2019-11-19 21:13
This has been fixed, default context options were wrong. Next release will contain fix.

**Comment by adimascio** [comment] 2019-11-19 21:58
> This has been fixed, default context options were wrong. Next release will contain fix.

This was quick, thanks!

**Comment by snowstakeda** [comment] 2019-12-04 16:50
v2.1.0 was released. If anybody has an problem, please file a new issue. Closing.

**Closed by snowstakeda** 2019-12-04 16:50 UTC
Labels: jira
