### ISSUE TITLE
SNOW-700665: Version 2.8.2 Crashing Jupyter Notebook

### ISSUE THREAD

**Issue by friendm** [snowflakedb/snowflake-connector-python#1352] opened 2022-11-28 19:42 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

  Python 3.9.13

2. What operating system and processor architecture are you using?

  Windows-10-10.0.19042-SP0

3. What are the component versions in the environment (`pip freeze`)?
snowflake-connector-python==2.8.2
  anaconda-client==1.11.0
anaconda-navigator==2.3.1
conda==22.9.0
conda-build==3.22.0

4. What did you do?

 I tried to run my Jupyter Notebook with the latest version of  snowflake-connector-python 2.82. The kernel crashes.
5. What did you expect to see?

Notebook should have functioned as normal. I was able to have the notebook run correctly by reverting to 2.8.1

6. Can you set logging to DEBUG and collect the logs?

  This cannot be done with the Jupyter Notebook, unfortunately

**Comment by sfc-gh-aling** [comment] 2022-11-28 20:04
thanks for reaching out we've identified one issue in v2.8.2 that will cause infinite loop if there're expired OCSP cache entries, wondering if that's the issue causing the trouble, we will get the fix to be released soon.

do you mind sharing us with your scripts so that I could verify it's caused by the same issue?

**Comment by friendm** [comment] 2022-11-29 15:33
I cannot share the script as it is something I use at work. However, the line of code that caused the issue was the connection string to the database. I used the authentication method "externalbrowser".
`` 
 conn = snowflake.connector.connect(
                user=USER,
                password=PASSWORD,
                account=ACCOUNT,
                warehouse=WAREHOUSE,
                  **authenticator='externalbrowser',**
                database=DATABASE,
                schema=SCHEMA
                )

``

**Comment by sfc-gh-aling** [comment] 2022-11-29 17:29
thanks for sharing the scripts, I will try to reproduce locally.
btw we've released 2.8.3 yesterday fixing a caching issue during connection establishment, do you mind taking a try on the newer version?

**Comment by marius-mather** [comment] 2022-11-30 04:58
I ran into this issue with version 2.8.2 today, and upgrading to 2.8.3 seems to have fixed it.

**Comment by sfc-gh-aling** [comment] 2022-12-01 00:05
glad to know it @marius-mather !
do you still encounter the issue with v2.8.3 @friendm ?

**Comment by friendm** [comment] 2022-12-01 15:27
Thanks for the quick response all. Yes the script is now working with the latest version, thanks again.

**Comment by sfc-gh-aling** [comment] 2022-12-01 17:49
thanks for letting us know it's resolved @friendm , I'm closing the issue now. feel free to reach out if you see any other issues.

**Closed by sfc-gh-aling** 2022-12-01 17:49 UTC
Labels: bug, needs triage
