### ISSUE TITLE
SNOW-892350: snowflake.connector.errors.InterfaceError: 252005

### ISSUE THREAD

**Issue by Mintactus** [snowflakedb/snowflake-connector-python#1694] opened 2023-08-14 14:15 UTC
### Python version

3.11.1

### Operating system and processor architecture

Linux-6.1.27-060127-generic-x86_64-with-glibc2.35

### Installed packages

```python
asn1crypto==1.5.1
oscrypto==1.3.0
platformdirs==3.8.1
pycryptodomex==3.18.0
PyJWT==2.8.0
pyOpenSSL==23.2.0
pytz==2023.3
snowflake-connector-python==3.1.0
sortedcontainers==2.4.0
urllib3==1.26.16
```

### What did you do?

```python
import snowflake.connector

# Create a connection object
snowflake_connection = snowflake.connector.connect(
    user='BONSAI_FIVETRAN_USER',
    password='fakepassword',
    account='fakeaccount',
    warehouse='WAREHOUSE',
    database='DATABASE',
    schema='SCHEMA'
)

# Queries
subscription_book_query = "SELECT * FROM A_TABLE_WITH_TIMESTAMPDATA"

# Create a cursor object.
cur = snowflake_connection.cursor()

# Execute a statement that will generate a result set.
cur.execute(subscription_book_query)


rows = []
# Fetch the results
for row in cur:
	rows.append(rows)
```

### What did you expect to see?

All the data from my SQL query

### Can you set logging to DEBUG and collect the logs?

```bash
snowflake.connector.errors.InterfaceError: 252005: Failed to convert current row, cause: <built-in method utcfromtimestamp of type object at 0x7f6f891bdf00> returned a result with an exception set
```

**Comment by sfc-gh-sfan** [comment] 2023-08-14 17:29
Can you provide a toy dataset for us to repro?

**Comment by sfc-gh-dszmolka** [comment] 2024-03-08 14:31
marking this issue as closed as it has been not responded to since quite a while. if you feel this is an issue with the Python Connector, please provide the reproduction dataset which when used for the query, reproduces the issue with the latest version of the connector and we can look further. Thank you !

**Closed by sfc-gh-dszmolka** 2024-03-08 14:31 UTC
