### ISSUE TITLE
SNOW-828173: `import snowflake.connector` now raises a warning about deprecated `pyopenssl` in `urllib3`

### ISSUE THREAD

**Issue by cpcloud** [snowflakedb/snowflake-connector-python#1586] opened 2023-05-26 11:32 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.10.11 (main, Apr  4 2023, 22:10:32) [GCC 12.2.0]

2. What operating system and processor architecture are you using?

   Linux-6.1.29-x86_64-with-glibc2.37

3. What are the component versions in the environment (`pip freeze`)?

```
❯ poetry show snowflake-connector-python
 name         : snowflake-connector-python
 version      : 3.0.3
 description  : Snowflake Connector for Python

dependencies
 - asn1crypto >0.24.0,<2.0.0
 - certifi >=2017.4.17
 - cffi >=1.9,<2.0.0
 - charset-normalizer >=2,<3
 - cryptography >=3.1.0,<41.0.0
 - filelock >=3.5,<4
 - idna >=2.5,<4
 - oscrypto <2.0.0
 - packaging *
 - pycryptodomex >=3.2,<3.5.0 || >3.5.0,<4.0.0
 - pyjwt <3.0.0
 - pyOpenSSL >=16.2.0,<24.0.0
 - pytz *
 - requests <3.0.0
 - typing-extensions >=4.3,<5
 - urllib3 >=1.21.1,<1.27

required by
 - snowflake-sqlalchemy <4.0.0
```

5. What did you do?

   `import snowflake.connector`

6. What did you expect to see?

   I expected to not see a warning.

7. Can you set logging to DEBUG and collect the logs?

   No.

https://github.com/urllib3/urllib3/issues/2680 is linked in the warning message

**Comment by waltervos** [comment] 2023-06-06 18:15
It seems like this import shouldn't be necessary, as snowflake-connector-python target python >= 3.7

**Comment by geofft** [comment] 2023-06-23 20:12
I _think_ this is coming from the vendored copy of urllib3 (see #521/#567 for some explanation of why) which is being monkey-patched by src/snowflake/connector/ssl_wrap_socket.py, and not from actual urllib3. And I think it's pointing to the fact that the vendored copy is quite a bit newer than the monkey patch. If the monkey patch were written against current urllib3, it wouldn't need urllib3.contrib.pyopenssl.

Also now that I look at the monkey patch closely I suspect it's buggy and mixing up `hostname_index` and `ssl_context_index`, so I'm not sure it is working right anyway....

(I don't really understand why there's both a vendored copy and a monkey patch. I guess it makes it easier to maintain the vendored copy, but I'd argue it makes it harder to make sure the monkey patch is still accurate.)

**Comment by ad-m-ss** [comment] 2023-08-03 15:35
@geofft could you confirm that you indent to reference #567 in your previous comment? It seems unrelated.

**Comment by sfc-gh-mkeller** [comment] 2023-09-27 03:50
I removed the warning in #1735, which doesn't mean that we should close this ticket!
We monkey-patch and vendor `urllib3` to have [OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) support. I know wish it was supported out-of-box by some HTTP library, but I haven't found one so far...
That said we'll need to find a new solution soon, as `urllib3` removed this module upstream.

**Comment by pquentin** [comment] 2023-09-28 12:13
For what it's worth, urllib3 2.0.5 (released on September 20th) undeprecated pyOpenSSL support: https://urllib3.readthedocs.io/en/stable/changelog.html, meaning that https://github.com/snowflakedb/snowflake-connector-python/pull/1735 could have been achieved by upgrading the vendored copy.

**Comment by sfc-gh-aling** [comment] 2024-03-08 19:40
with the latest connector, we have bumped our vendored dependency and I didn't see deprecation warning.
I assume the issue is gone and close the issue now. Please feel free to reach out if you still see the issue.

**Closed by sfc-gh-aling** 2024-03-08 19:40 UTC
Labels: bug, needs triage

**Comment by afeld** [comment] 2025-05-23 02:20
(That was bumped in [3.7.1](https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v3.7.1), if anyone's curious.)
