### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by jallen1788** [snowflakedb/snowflake-connector-python#31] opened 2017-08-09 15:24 UTC
When attempting to connect to the snowflake engine:
```
import snowflake.connector
cnx = snowflake.connector.connect(user=***, password=***, account=***)
```

I get the following stack trace. Take note of line 3 `who is hitting error?` which shows up here: https://github.com/snowflakedb/snowflake-connector-python/blob/13cf42ccf1d72563baa59f0b9ae5790c6733d9c1/network.py#L760
```
Snowflake Connector for Python Version: 1.3.17, Python Version: 2.7.12, Platform: Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
Starting new HTTPS connection (1): ***.snowflakecomputing.com
who is hitting error?
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/network.py", line 704, in request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/ssl_wrap_socket.py", line 469, in ssl_wrap_socket_with_ocsp
    ssl_version=ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/ssl_wrap_socket.py", line 452, in ssl_wrap_socket
    rd, _, _ = select.select([sock], [], [], sock.gettimeout())
ValueError: filedescriptor out of range in select()
```

I was able to remedy the issue by restarting the container.

**Comment by smtakeda** [comment] 2017-08-09 18:56
Does this happen constantly or intermittently? The query was success eventually or not?

In general, connection fails for various reasons, and Python Connector retries until hang or success. Currently the authentication timeouts 120 seconds and query will retry forever. This log should not have showed up in case of success. To reduce confusion, the commit (https://github.com/snowflakedb/snowflake-connector-python/commit/13cf42ccf1d72563baa59f0b9ae5790c6733d9c1) changed the error level from ERROR to DEBUG.

**Comment by jallen1788** [comment] 2017-08-09 19:03
Once it got into this state, it stayed in a bad state and never succeeded. Only restarting the container remedied the issue. After restart, it appears to be working, but I am worried that after some amount of time, it will get into this same bad state again and require another restart.

**Comment by smtakeda** [comment] 2017-08-10 16:36
hmm sounds like the very low level communication was messed up. will try to dig into this.

**Comment by jallen1788** [comment] 2017-08-16 13:58
We encountered this issue again today. Same details as last time. Is there any information we can gather that might help?

**Comment by smtakeda** [comment] 2017-08-16 18:59
Googled the similar error message and found the cause seems too many files are opened and the FD got out of range. Can you try increasing the open file limit?

Meanwhile I'm attempting to port the latest `urlib3` code that has some improvements in use of select, i.e., kqueue, epoll, poll are used instead of select.

**Comment by jallen1788** [comment] 2017-08-16 20:12
Since it takes 7 days to reach this error, I'm hesitant to increase the open file limit since it will only mask the problem (might take 14 days instead of 7 to observe). It also may introduce other side effects on the system due to an unreasonable amount of open files.

**Comment by brln** [comment] 2017-08-16 22:48
I am also running into this error intermittently, causing me lots of problems:

`
2017-08-16 22:43:47,156 - ERROR - (snowflake.connector.errors.OperationalError) 250003: Failed to execute request: filedescriptor out of range in select()
Traceback (most recent call last):
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 1044, in _do_get
    return self._pool.get(wait, self._timeout)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/queue.py", line 145, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/__init__.py", line 32, in Connect
    return SnowflakeConnection(**kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 116, in __init__
    self.connect(**kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 268, in connect
    'password_callback'))
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 451, in __open_connection
    session_parameters=self._session_parameters,
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 334, in authenticate
    timeout=self._connection._login_timeout)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 600, in _post_request
    is_single_thread=is_single_thread)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 662, in fetch
    proxies, timeouts, **kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 905, in _fetch
    u'errno': ER_FAILED_TO_REQUEST,
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/errors.py", line 99, in errorhandler_wrapper
    connection.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/errors.py", line 72, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.OperationalError: 250003: Failed to execute request: filedescriptor out of range in select()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/current/app/helpers/worker.py", line 354, in start_worker
    keep_working = do_work(task)
  File "/opt/python/current/app/helpers/worker.py", line 410, in do_work
    raise e
  File "/opt/python/current/app/helpers/worker.py", line 394, in do_work
    output = globals()[taskname](input, heartbeat_func, taskname, token)
  File "/opt/python/current/app/helpers/worker.py", line 254, in insert_local_data
    bucket
  File "/opt/python/current/app/helpers/snowflake.py", line 298, in make_stage
    session.execute(create_stage_cmd)
  File "/opt/python/current/app/helpers/snowflake.py", line 22, in execute
    resp = self.actual_session.execute(*args, **kwargs)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 1034, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/__init__.py", line 32, in Connect
    return SnowflakeConnection(**kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 116, in __init__
    self.connect(**kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 268, in connect
    'password_callback'))
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/connection.py", line 451, in __open_connection
    session_parameters=self._session_parameters,
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 334, in authenticate
    timeout=self._connection._login_timeout)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 600, in _post_request
    is_single_thread=is_single_thread)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 662, in fetch
    proxies, timeouts, **kwargs)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/network.py", line 905, in _fetch
    u'errno': ER_FAILED_TO_REQUEST,
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/errors.py", line 99, in errorhandler_wrapper
    connection.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/opt/python/run/venv/lib/python3.4/site-packages/snowflake/connector/errors.py", line 72, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
sqlalchemy.exc.OperationalError: (snowflake.connector.errors.OperationalError) 250003: Failed to execute request: filedescriptor out of range in select()
`

**Comment by smtakeda** [comment] 2017-08-24 16:59
The improvement was committed in https://github.com/snowflakedb/snowflake-connector-python/commit/1cdeb3c547c858358c85483f5c54ccd7efe37a77

**Comment by smtakeda** [comment] 2017-08-31 18:55
Is this incident still happening?

**Comment by jallen1788** [comment] 2017-08-31 19:21
I haven't had the change to upgrade and test, but plan to do so soon.

**Comment by smtakeda** [comment] 2018-01-13 17:20
Not sure if this issue persist. Closing the issue for now. Reopen or file a new issue if you still see it. Thanks.

**Closed by smtakeda** 2018-01-13 17:20 UTC
Labels: bug

**Comment by jallen1788** [comment] 2018-01-13 17:45
Fixed!
