### ISSUE TITLE
maximum number of expressions in a list exceeded, expected at most 16,384, got 190,800

### ISSUE THREAD

**Issue by JDFagan** [snowflakedb/snowflake-connector-python#37] opened 2017-09-27 22:29 UTC
Snowflake connector seems to have limitation of accepting large sets at once (> 16,384 items).  Would be nice to substantially increase this limit.  My code is simply trying to upload a large (190k) csv file via use of Agate and SQLAlchemy.  This code works fine when targeting against RDS MySQL 5.6.

```
Creating transformer_loader for /Users/jdfagan/tmp/property_ledger/LIONSTONEGRP/transform/GLSummary.csv ...
Loading source: /Users/jdfagan/tmp/property_ledger/LIONSTONEGRP/transform/transform/GLSummary.csv ...
database table: LIONSTONEGRP_GLSummary
| column     | data_type |
| ---------- | --------- |
| AccountID  | Number    |
| AcctNum    | Text      |
| EntityID   | Text      |
| Department | Text      |
| Basis      | Text      |
| Period     | Text      |
| PeriodDate | Date      |
| Balfor     | Text      |
| Activity   | Number    |

FAILED
etl/mri/test_property_ledger_etl.py:109 (test_MriPropertyLedgerETL_load[LIONSTONEGRP])
self = <sqlalchemy.engine.base.Connection object at 0x10fe42438>
dialect = <snowflake.sqlalchemy.base.SnowflakeDialect object at 0x10fe42080>
constructor = <bound method DefaultExecutionContext._init_compiled of <class 'snowflake.sqlalchemy.base.SnowflakeExecutionContext'>>
statement = 'INSERT INTO "LIONSTONEGRP_GLSummary" ("AccountID", "AcctNum", "EntityID", "Department", "Basis", "Period", "PeriodDat...countID)s, %(AcctNum)s, %(EntityID)s, %(Department)s, %(Basis)s, %(Period)s, %(PeriodDate)s, %(Balfor)s, %(Activity)s)'
parameters = ({'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('-99.37'), 'Balfor': 'B', ...}, {'Accoun......}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('300.00'), 'Balfor': 'B', ...}, ...)
args = (<snowflake.sqlalchemy.base.SnowflakeCompiler object at 0x10fe425c0>, [{'AccountID': Decimal('1001000'), 'AcctNum': '1.....}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('300.00'), 'Balfor': 'B', ...}, ...])
conn = <sqlalchemy.pool._ConnectionFairy object at 0x10fe541d0>
context = <snowflake.sqlalchemy.base.SnowflakeExecutionContext object at 0x10fe429b0>

    def _execute_context(self, dialect, constructor,
                         statement, parameters,
                         *args):
        """Create an :class:`.ExecutionContext` and execute, returning
            a :class:`.ResultProxy`."""
    
        try:
            try:
                conn = self.__connection
            except AttributeError:
                conn = self._revalidate_connection()
    
            context = constructor(dialect, self, conn, *args)
        except BaseException as e:
            self._handle_dbapi_exception(
                e,
                util.text_type(statement), parameters,
                None, None)
    
        if context.compiled:
            context.pre_exec()
    
        cursor, statement, parameters = context.cursor, \
            context.statement, \
            context.parameters
    
        if not context.executemany:
            parameters = parameters[0]
    
        if self._has_events or self.engine._has_events:
            for fn in self.dispatch.before_cursor_execute:
                statement, parameters = \
                    fn(self, cursor, statement, parameters,
                       context, context.executemany)
    
        if self._echo:
            self.engine.logger.info(statement)
            self.engine.logger.info(
                "%r",
                sql_util._repr_params(parameters, batches=10)
            )
    
        evt_handled = False
        try:
            if context.executemany:
                if self.dialect._has_events:
                    for fn in self.dialect.dispatch.do_executemany:
                        if fn(cursor, statement, parameters, context):
                            evt_handled = True
                            break
                if not evt_handled:
                    self.dialect.do_executemany(
                        cursor,
                        statement,
                        parameters,
>                       context)

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:1159: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <snowflake.sqlalchemy.base.SnowflakeDialect object at 0x10fe42080>
cursor = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
statement = 'INSERT INTO "LIONSTONEGRP_GLSummary" ("AccountID", "AcctNum", "EntityID", "Department", "Basis", "Period", "PeriodDat...countID)s, %(AcctNum)s, %(EntityID)s, %(Department)s, %(Basis)s, %(Period)s, %(PeriodDate)s, %(Balfor)s, %(Activity)s)'
parameters = ({'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('-99.37'), 'Balfor': 'B', ...}, {'Accoun......}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('300.00'), 'Balfor': 'B', ...}, ...)
context = <snowflake.sqlalchemy.base.SnowflakeExecutionContext object at 0x10fe429b0>

    def do_executemany(self, cursor, statement, parameters, context=None):
>       cursor.executemany(statement, parameters)

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/default.py:467: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
command = 'INSERT INTO "LIONSTONEGRP_GLSummary" ("AccountID", "AcctNum", "EntityID", "Department", "Basis", "Period", "PeriodDat...B\', \'3252.70\'),(\'9999000\', \'9999-000\', \'SDTCRS\', \'@\', \'C\', \'01/16\', \'2016-01-01\', \'B\', \'3252.70\')'
seqparams = ({'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('-99.37'), 'Balfor': 'B', ...}, {'Accoun......}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'Activity': Decimal('300.00'), 'Balfor': 'B', ...}, ...)

    def executemany(self, command, seqparams):
        u"""
            Executes a command/query with the given set of parameters sequentially.
            """
        logger.info(u'executing many SQLs/commands')
        command = command.strip(u' \t\n\r') if command else None
    
        if self.INSERT_SQL_RE.match(command):
            logger.debug(u'rewriting INSERT query')
            command_wo_comments = re.sub(self.COMMENT_SQL_RE, u'', command)
            m = self.INSERT_SQL_VALUES_RE.match(command_wo_comments)
            if not m:
                errorvalue = {
                    u'msg': u"Failed to rewrite multi-row insert",
                    u'errno': ER_FAILED_TO_REWRITE_MULTI_ROW_INSERT
                }
                Error.errorhandler_wrapper(
                    self.connection, self, InterfaceError, errorvalue
                )
    
            fmt = m.group(1)
            values = []
            for param in seqparams:
                logger.debug(u'parameter: %s', param)
                values.append(fmt % self.__process_params(param))
            command = command.replace(fmt, u','.join(values), 1)
>           self.execute(command)

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/cursor.py:666: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
command = 'INSERT INTO "LIONSTONEGRP_GLSummary" ("AccountID", "AcctNum", "EntityID", "Department", "Basis", "Period", "PeriodDat...B\', \'3252.70\'),(\'9999000\', \'9999-000\', \'SDTCRS\', \'@\', \'C\', \'01/16\', \'2016-01-01\', \'B\', \'3252.70\')'
params = None, timeout = None, _do_reset = True, _put_callback = None
_put_callback_output_stream = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
_get_callback = None
_get_callback_output_stream = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
_statement_params = None, _is_internal = False, _no_results = False
_use_ijson = False, _is_put_get = None

    def execute(self, command, params=None, timeout=None,
                _do_reset=True,
                _put_callback=None,
                _put_callback_output_stream=sys.stdout,
                _get_callback=None,
                _get_callback_output_stream=sys.stdout,
                _statement_params=None,
                _is_internal=False,
                _no_results=False,
                _use_ijson=False,
                _is_put_get=None):
        u"""
            Executes a command/query
            """
        logger.debug(u'executing SQL/command')
        if self.is_closed():
            Error.errorhandler_wrapper(
                self.connection, self,
                DatabaseError,
                {u'msg': u"Cursor is closed in execute.",
                 u'errno': ER_CURSOR_IS_CLOSED})
    
        if _do_reset:
            self.reset()
        command = command.strip(u' \t\n\r') if command else None
        if not command:
            logger.warning(u'execute: no query is given to execute')
            return
    
        processed_params = self.__process_params(params)
        logger.debug(u'binding: %s with input=%s, processed=%s',
                     command,
                     params, processed_params)
        if len(processed_params) > 0:
            query = command % processed_params
        else:
            query = command
    
        if logger.getEffectiveLevel() <= logging.DEBUG:
            logger.debug(
                u'query: [%s]',
                u' '.join(line.strip() for line in query.split(u'\n')))
        m = DESC_TABLE_RE.match(query)
        if m:
            query1 = u'describe table {0}'.format(m.group(1))
            if logger.getEffectiveLevel() <= logging.WARNING:
                logger.warning(
                    u'query was rewritten: org=%s, new=%s',
                    u' '.join(line.strip() for line in query.split(u'\n')),
                    query1
                )
            query = query1
    
        ret = self._execute_helper(query, timeout=timeout,
                                   statement_params=_statement_params,
                                   is_internal=_is_internal,
                                   _no_results=_no_results,
                                   _is_put_get=_is_put_get)
        self._sfqid = ret[u'data'][
            u'queryId'] if u'data' in ret and u'queryId' in ret[
            u'data'] else None
        self._sqlstate = ret[u'data'][
            u'sqlState'] if u'data' in ret and u'sqlState' in ret[
            u'data'] else None
        logger.debug('sfqid: %s', self.sfqid)
    
        if ret[u'success']:
            logger.debug(u'SUCCESS')
            data = ret[u'data']
            if u'finalDatabaseName' in data:
                self._connection._database = data[u'finalDatabaseName']
            if u'finalSchemaName' in data:
                self._connection._schema = data[u'finalSchemaName']
            if u'finalWarehouseName' in data:
                self._connection._warehouse = data[u'finalWarehouseName']
            if u'finalRoleName' in data:
                self._connection._role = data[u'finalRoleName']
    
            # logger.debug(ret)
            logger.debug(u"PUT OR GET: %s", self.is_file_transfer)
            if self.is_file_transfer:
                sf_file_transfer_agent = SnowflakeFileTransferAgent(
                    self, query, ret,
                    put_callback=_put_callback,
                    put_callback_output_stream=_put_callback_output_stream,
                    get_callback=_get_callback,
                    get_callback_output_stream=_get_callback_output_stream)
                sf_file_transfer_agent.execute()
                data = sf_file_transfer_agent.result()
                self._total_rowcount = len(data[u'rowset']) if \
                    u'rowset' in data else -1
            m = self.ALTER_SESSION_RE.match(query)
            if m:
                # session parameters
                param = m.group(1).upper()
                value = m.group(2)
                self._connection.converter.set_parameter(param, value)
    
            if _no_results:
                self._total_rowcount = ret[u'data'][
                    u'total'] if u'data' in ret and u'total' in ret[
                    u'data'] else -1
                return data
            self.chunk_info(data, use_ijson=_use_ijson)
        else:
            self._total_rowcount = ret[u'data'][
                u'total'] if u'data' in ret and u'total' in ret[u'data'] else -1
            logger.debug(ret)
            err = ret[u'message']
            code = ret.get(u'code', -1)
            if u'data' in ret and u'errorMessage' in ret[u'data']:
                err += ret[u'data'][u'errorMessage']
            errvalue = {
                u'msg': err,
                u'errno': int(code),
                u'sqlstate': self._sqlstate,
                u'sfqid': self._sfqid
            }
            Error.errorhandler_wrapper(self.connection, self,
                                       ProgrammingError,
>                                      errvalue)

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/cursor.py:526: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

connection = <snowflake.connector.connection.SnowflakeConnection object at 0x10fe42c50>
cursor = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
errorclass = <class 'snowflake.connector.errors.ProgrammingError'>
errorvalue = {'done_format_msg': False, 'errno': 1795, 'msg': 'SQL compilation error: error line 1 at position 143\nmaximum number ...ssions in a list exceeded, expected at most 16,384, got 190,800', 'sfqid': 'c56de412-761c-44d6-b202-5867134658cc', ...}

    @staticmethod
    def errorhandler_wrapper(connection, cursor, errorclass, errorvalue=None):
        u"""
            Error handler wrapper that calls the errorhandler method
            """
        if errorvalue is None:
            # no value indicates errorclass is errorobject
            errorobject = errorclass
            errorclass = type(errorobject)
            errorvalue = {
                u'msg': errorobject.msg,
                u'errno': errorobject.errno,
                u'sqlstate': errorobject.sqlstate,
                u'done_format_msg': True
            }
        else:
            errorvalue[u'done_format_msg'] = False
    
        if connection is not None:
            connection.messages.append((errorclass, errorvalue))
        if cursor is not None:
            cursor.messages.append((errorclass, errorvalue))
>           cursor.errorhandler(connection, cursor, errorclass, errorvalue)

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/errors.py:97: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

connection = <snowflake.connector.connection.SnowflakeConnection object at 0x10fe42c50>
cursor = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
errorclass = <class 'snowflake.connector.errors.ProgrammingError'>
errorvalue = {'done_format_msg': False, 'errno': 1795, 'msg': 'SQL compilation error: error line 1 at position 143\nmaximum number ...ssions in a list exceeded, expected at most 16,384, got 190,800', 'sfqid': 'c56de412-761c-44d6-b202-5867134658cc', ...}

    @staticmethod
    def default_errorhandler(connection, cursor, errorclass, errorvalue):
        u"""
            Default error handler that raises an error
            """
        raise errorclass(
            msg=errorvalue.get(u'msg'),
            errno=errorvalue.get(u'errno'),
            sqlstate=errorvalue.get(u'sqlstate'),
            sfqid=errorvalue.get(u'sfqid'),
>           done_format_msg=errorvalue.get(u'done_format_msg'))
E       snowflake.connector.errors.ProgrammingError: 001795 (42601): SQL compilation error: error line 1 at position 143
E       maximum number of expressions in a list exceeded, expected at most 16,384, got 190,800

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/errors.py:73: ProgrammingError

The above exception was the direct cause of the following exception:

client = 'LIONSTONEGRP'

    @pytest.mark.parametrize("client", clients)
    def test_MriPropertyLedgerETL_load(client: str):
        etl = MriPropertyLedgerETL(client_database=client, etl_dir="{}{}".format(ETL_DIR_BASE, client))
>       etl.load()

etl/mri/test_property_ledger_etl.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../waypoint/etl/property_ledger_etl.py:80: in load
    loader.from_csv().to_sql(database_url, self.client_code)
../../waypoint/etl/mri/transformer_loader.py:89: in to_sql
    self.table.to_sql(database_url, table_name, overwrite=True)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/agatesql/table.py:219: in to_sql
    connection.execute(insert, [dict(zip(self.column_names, row)) for row in self.rows])
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:945: in execute
    return meth(self, multiparams, params)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/sql/elements.py:263: in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:1053: in _execute_clauseelement
    compiled_sql, distilled_params
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:1189: in _execute_context
    context)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:1402: in _handle_dbapi_exception
    exc_info
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/util/compat.py:203: in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/util/compat.py:186: in reraise
    raise value.with_traceback(tb)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/base.py:1159: in _execute_context
    context)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/sqlalchemy/engine/default.py:467: in do_executemany
    cursor.executemany(statement, parameters)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/cursor.py:666: in executemany
    self.execute(command)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/cursor.py:526: in execute
    errvalue)
/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/errors.py:97: in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

connection = <snowflake.connector.connection.SnowflakeConnection object at 0x10fe42c50>
cursor = <snowflake.connector.cursor.SnowflakeCursor object at 0x10fe42eb8>
errorclass = <class 'snowflake.connector.errors.ProgrammingError'>
errorvalue = {'done_format_msg': False, 'errno': 1795, 'msg': 'SQL compilation error: error line 1 at position 143\nmaximum number ...ssions in a list exceeded, expected at most 16,384, got 190,800', 'sfqid': 'c56de412-761c-44d6-b202-5867134658cc', ...}

    @staticmethod
    def default_errorhandler(connection, cursor, errorclass, errorvalue):
        u"""
            Default error handler that raises an error
            """
        raise errorclass(
            msg=errorvalue.get(u'msg'),
            errno=errorvalue.get(u'errno'),
            sqlstate=errorvalue.get(u'sqlstate'),
            sfqid=errorvalue.get(u'sfqid'),
>           done_format_msg=errorvalue.get(u'done_format_msg'))
E       sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001795 (42601): SQL compilation error: error line 1 at position 143
E       maximum number of expressions in a list exceeded, expected at most 16,384, got 190,800 [SQL: 'INSERT INTO "LIONSTONEGRP_GLSummary" ("AccountID", "AcctNum", "EntityID", "Department", "Basis", "Period", "PeriodDate", "Balfor", "Activity") VALUES (%(AccountID)s, %(AcctNum)s, %(EntityID)s, %(Department)s, %(Basis)s, %(Period)s, %(PeriodDate)s, %(Balfor)s, %(Activity)s)'] [parameters: ({'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': '2525OF', 'Department': '@', 'Basis': 'A', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('-99.37')}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': '2525OF', 'Department': '@', 'Basis': 'C', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('-99.37')}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': '2525WE', 'Department': '@', 'Basis': 'A', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('99.37')}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': '712MAI', 'Department': '@', 'Basis': 'A', 'Period': '07/16', 'PeriodDate': datetime.date(2016, 7, 1), 'Balfor': 'B', 'Activity': Decimal('300.00')}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': 'CTYCTR', 'Department': '@', 'Basis': 'A', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('300.00')}, {'AccountID': Decimal('1001000'), 'AcctNum': '1001-000', 'EntityID': 'GSLTDP', 'Department': '@', 'Basis': 'A', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('300.00')}, {'AccountID': Decimal('1002001'), 'AcctNum': '1002-001', 'EntityID': '110ATR', 'Department': '@', 'Basis': 'A', 'Period': '11/16', 'PeriodDate': datetime.date(2016, 11, 1), 'Balfor': 'N', 'Activity': Decimal('440667.35')}, {'AccountID': Decimal('1002001'), 'AcctNum': '1002-001', 'EntityID': '110ATR', 'Department': '@', 'Basis': 'A', 'Period': '12/16', 'PeriodDate': datetime.date(2016, 12, 1), 'Balfor': 'N', 'Activity': Decimal('339664.73')}  ... displaying 10 of 190800 total bound parameter sets ...  {'AccountID': Decimal('9999000'), 'AcctNum': '9999-000', 'EntityID': 'SDTCRS', 'Department': '@', 'Basis': 'A', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('3252.70')}, {'AccountID': Decimal('9999000'), 'AcctNum': '9999-000', 'EntityID': 'SDTCRS', 'Department': '@', 'Basis': 'C', 'Period': '01/16', 'PeriodDate': datetime.date(2016, 1, 1), 'Balfor': 'B', 'Activity': Decimal('3252.70')})]

/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/errors.py:73: ProgrammingError
```

Below is my environment:

```
name: waypoint_extraction
channels:
- conda-forge
- defaults
- asmeurer
- snowflakedb
dependencies:
- agate=1.6.0=py36_2
- agate-dbf=0.2.0=py36_0
- agate-excel=0.2.1=py36_0
- agate-sql=0.5.2=py36_0
- asn1crypto=0.22.0=py36_0
- babel=2.4.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- coverage=4.4.1=py36_0
- cryptography=2.0.3=py36_0
- csvkit=1.0.2=py36_0
- dbfread=2.0.7=py36_0
- et_xmlfile=1.0.1=py36_0
- isodate=0.5.4=py36_0
- jdcal=1.3=py36_0
- leather=0.3.3=py36_0
- libffi=3.2.1=3
- mysql-connector-python=2.2.2=py36_0
- ncurses=5.9=10
- openpyxl=2.5.0a3=py36_0
- openssl=1.0.2l=0
- parsedatetime=2.4=py36_0
- pip=9.0.1=py36_0
- py=1.4.34=py36_0
- pycparser=2.18=py36_0
- pyopenssl=17.2.0=py36_0
- pysocks=1.6.7=py36_0
- pytest=3.2.2=py_0
- pytest-cov=2.5.1=py36_0
- python=3.6.2=0
- python-slugify=1.2.4=py36_1
- pytimeparse=1.1.7=py36_0
- pytz=2017.2=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- requests-toolbelt=0.8.0=py36_0
- setuptools=36.3.0=py36_0
- six=1.10.0=py36_1
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- unidecode=0.04.21=py36_0
- urllib3=1.22=py36_0
- wheel=0.29.0=py36_0
- xlrd=1.1.0=py36_1
- xz=5.2.3=0
- zlib=1.2.11=0
- idna=2.6=py36_0
- pymysql=0.7.9=py36_0
- pip:
  - boto3==1.4.6
  - botocore==1.6.8
  - docutils==0.14
  - et-xmlfile==1.0.1
  - future==0.16.0
  - hvac==0.2.17
  - ijson==2.3
  - jmespath==0.9.3
  - pyasn1==0.2.3
  - pyasn1-modules==0.0.9
  - pycryptodome==3.4.7
  - python-dateutil==2.6.1
  - s3transfer==0.1.11
  - snowflake-connector-python==1.4.6
  - snowflake-sqlalchemy==1.0.7
prefix: /Users/jdfagan/miniconda3/envs/waypoint_extraction
```

**Comment by smtakeda** [comment] 2017-09-28 00:45
Yeah, that's a kind of limitation how the connector ingest data. The cause looks like INSERT with multiple values hits our SQL parser's limitation. Can you try chunksize option?
```
to_sql(..., chunksize=10000)
```

**Comment by JDFagan** [comment] 2017-09-28 17:44
I didn't see chunksize as a parameter for agate-sql in their docs (http://agate-sql.readthedocs.io/en/0.5.2/#api).  Is that what you were referring to re: chunksize or a different API?

**Comment by smtakeda** [comment] 2017-09-28 20:00
Oh, I thought this https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html
Need to look into how agate-sql wraps.

**Comment by smtakeda** [comment] 2017-11-10 18:16
Sent PR to agatesql to support `chunksize` parameter to `to_sql`
https://github.com/wireservice/agate-sql/pull/29

**Comment by smtakeda** [comment] 2018-01-27 23:39
FYI, @JDFagan , agate-sql merged the fix.

**Closed by smtakeda** 2018-01-27 23:39 UTC
Labels: bug, enhancement

**Comment by RiteshM1993** [comment] 2018-02-14 05:18
Hi smtakeda
i made a script for loading the data from sql server to snowflake we have tried to load 1.5millions to record into snowflake and that worked fine for me but it took more than half hour to perform it and load the data in chunks i.e chunksize= 15000 i believe it snowflake limitation is 16000 .
so i want to load 50 millions of data into snowflake with python script
my question is how we can increase the chunksize of snowflake and and how can increase the performance .
please suggest?

below is the code

mport pandas as pd
from sqlalchemy import *
import snowflake.connector

try:
    # ms Sql Connnection
    mssql_engine = create_engine('mssql+pymssql://SA:Admin123@localhost:1433/testdb')
    conn = mssql_engine.connect()
    print "Connected To Ms SQl using Sql Alchemy..."

    # Snowflake connector
    snowflake_conn = snowflake.connector.connect(user='snehal',password='Test@1234',account='decisionminds',)
    snowflake_cursor = snowflake_conn.cursor()
    print "Connected to Snowflake..."

    if snowflake_cursor:
        snowflake_cursor.execute("CREATE DATABASE IF NOT EXISTS ms_to_sql_testdb")
        snowflake_cursor.execute("USE DATABASE ms_to_sql_testdb")
        snowflake_cursor.execute("CREATE SCHEMA IF NOT EXISTS ms_to_sql_testdb_schema")
        snowflake_cursor.execute("USE SCHEMA ms_to_sql_testdb_schema")

        # Snow Flake SQL Alchemy connection
        snw_flk_engine = create_engine(
            'snowflake://{user}:{password}@{account}/{db}'.format(user='snehal', password='Test@1234',account='decisionminds', db='ms_to_sql_testdb'))
        snw_flk_conn = snw_flk_engine.connect()
        print "Connected to SQL Alchemy..."
        #  for loop to fetch dataframe

        if snw_flk_conn:
            count = 1
            for data in pd.read_sql_query('SELECT * FROM onelakhrecords', conn,chunksize=16000):
                results = data.to_sql("onelakhrecords", snw_flk_conn, if_exists='append',index=False,index_label=None, schema='ms_to_sql_testdb_schema')
                print str(count) + ' Chunk Uploaded...'
                count += 1
            print 'data uploaded successfully'
        else:
            print "Snow Flake Connection error"
    else:
        print "An error occured while inserting a table"

except Exception as error:
    print  error
    print "Connection error"

finally:
    snowflake_cursor.close()
    conn.close()
    snw_flk_conn.close()

**Comment by smtakeda** [comment] 2018-02-14 05:52
@RiteshM1993 the limitation came from the size of SQL, e.g., `INSERT INTO` followed by all data in a single statement implemented in `executemany`

can you try the connection parameter `paramstyle=qmark`? It is undocumented, but I believe it is worth to try. Binding data happens in the server end instead of composing a sql in the clients

 If any issue is found, please file a new issue. This is issue was already closed, so it would be easier for us to track the open issue separately.

**Comment by kenbier** [comment] 2018-06-11 22:42
I hit this as well, passing a list of 25k rows into execute many. Changing the paramstyle=qmark did solve the issue. This should be documented imo, the current docs are very confusing in this regard. Thanks.

**Comment by smtakeda** [comment] 2018-06-12 02:00
@kenbier good to know the qmark actually worked! Will try to update the doc as soon as possible.

**Comment by smtakeda** [comment] 2018-06-13 02:19
Looks like `qmark` is already in the doc: https://docs.snowflake.net/manuals/user-guide/python-connector-api.html#paramstyle

I guess part of confusion came from the fact Snowflake Python Connector supports both `pyformat` and `qmark`, while others don't. It is more or less historical reason. No binding was supported by the Snowflake DB when I wrote Python Connector so `pyformat` was the only choice. Later the server side binding was added, then the customers came across the SQL length limitation and made me decide to implement `qmark` support.

**Comment by ztane** [comment] 2019-04-17 05:20
This issue is not resolved. The problem rather is that the `executemany` cannot compile to a single statement, and it should be issue several inserts in a loop instead.

**Comment by smtakeda** [comment] 2019-04-18 02:22
Maybe `paramstyle=qmark` should be default due to more demand of bulk binding?
`paramstyle=pyformat` exists merely because historical reason. When the Python connector was implemented, no server side binding was supported...

**Comment by michael135** [comment] 2020-11-18 09:36
> chunksize=10000

This worked for me!
Thank you!
