### ISSUE TITLE
SNOW-151365: fetch_pandas_all() not working - looks to be an issue with pyarrow from log

### ISSUE THREAD

**Issue by tomslade1** [snowflakedb/snowflake-connector-python#295] opened 2020-04-08 13:53 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
**Python 3.8.1**

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
**Windows-10-10.0.17763-SP0**

3. What are the component versions in the environment (`pip list`)? 
**Attached - requirements.txt**
[requirements.txt](https://github.com/snowflakedb/snowflake-connector-python/files/4450849/requirements.txt)

4. What did you do?
``` Python
import snowflake.connector
import pandas as pd

ctx = snowflake.connector.connect(
          user='XXXX',
          password='XXXX',
          account='XXXX',
          protocol='https')

# Create a cursor object.
cur = ctx.cursor()

# Execute a statement that will generate a result set.
sql = """
         select *

         from DATABASE.SCHEMA.TABLE

         limit 10
         """
cur.execute(sql)

df = cur.fetch_pandas_all()
print(df.head())
```

5. What did you expect to see?
**df head**

6. What did you see instead?
**Raised error: "snowflake.connector.errors.NotSupportedError: Unknown error" but query runs fine using SQLAlchemy & pd.read_sql() approach though.**

7. Can you set logging to DEBUG and collect the logs?
**Attached logs - API.log**
[API.log](https://github.com/snowflakedb/snowflake-connector-python/files/4450848/API.log)

**Comment by keller00** [comment] 2020-04-08 17:19
Hi @tomslade1 , we don't support pyarrow on Windows 10 with Python 3.8 yet for this reason. Sorry for the inconvenience, we're working on it!

**Comment by tomslade1** [comment] 2020-04-08 17:42
Thanks for the clarification @keller00! Will close this for now then - any rough ideas when the release will be ready?

**Comment by keller00** [comment] 2020-04-08 20:02
No, unfortunately. We're working on this right now, but this is a an error that doesn't show itself during build (as you probably have seen this; side note: this is the reason why there's no wheel for this os and version combination on PyPi). It only fails **every** test after it builds successfully??

**Comment by xhochy** [comment] 2020-04-09 07:15
The error in the log looks quite unspecific. @keller00 Do you have more context on this? `pyarrow` wheels for 3.8 shouldn't behave differently than those for 3.6 or 3.7.

**Comment by keller00** [comment] 2020-04-09 17:49
First let me reopen this ticket, because others will be opening new tickets about the same issue.
@xhochy I don't see any errors in the attached log and at the end it says that it was using json and not arrow.
When I was manually compiling the wheel for Windows with Python 3.8 I was getting a generic dll issue then I looked through some of the generated cython code and it looked identical to 3.7 code. So maybe compilation issue, but I am really stomped on this.
If anyone would like to take a crack at this, see how we compile our code here: https://github.com/snowflakedb/snowflake-connector-python/blob/master/scripts/build_pyarrow.bat

**Comment by xhochy** [comment] 2020-04-13 06:19
Thanks @keller00 for the hint. I did take a shot at compiling the 3.8 wheel and it passed for me without an error: https://gist.github.com/xhochy/65fdcacc427102951ebcfea9ceaa4066

**Comment by keller00** [comment] 2020-04-13 08:40
That’s where the interesting part of this issue lies, @xhochy
While it compiles try installing it and importing `snowflake.connector.arrow_iterator`. That’s where you will see the issue.
Now we think the issue comes from: https://docs.python.org/3/library/os.html#os.add_dll_directory (see the note about Python 3.8), but we don’t have a fix for this yet.

**Comment by xhochy** [comment] 2020-04-13 08:42
Good to know. We have actually the same (yet unresolved) issue in turbodbc on Windows and Python 3.8.

**Comment by SG-lunch** [comment] 2020-04-13 18:11
Hi @xhochy, we tried `add_dll_directory` solution, which looks like a fix for some guys but not for us yet. Would you mind sharing your trial of this with us if you try it? That would be very helpful!

**Comment by chetansurwade** [comment] 2020-04-18 16:10
> 2\. fine using SQLAlchemy & pd.read_sql() approach though.

As you said, using sqlalchemy with pd.read_sql() it works fine with https://github.com/snowflakedb/snowflake-sqlalchemy and you should probably stick with it, its much cleaner. You could use something like this ->

`def get_engine(database: str = "", schema: str = "") -> sqlalchemy.engine.Engine:
    """Function to get snowflake-sqlalchemy engine object.

    :param database: Database Name., defaults to ""
    :type database: str, optional
    :param schema: Schema Name., defaults to ""
    :type schema: str, optional
    :return: Returns a :class:`sqlalchemy.engine.Engine` object with connection details specified and empty object if connection fails.
    :rtype: sqlalchemy.engine.Engine
    """
    configuration = config.SnowConfig()
    engine = sqlalchemy.engine.Engine
    try:
        if database and schema:
            engine = sqlalchemy.create_engine(URL(
                account=configuration.account,
                user=configuration.username,
                password=configuration.password,
                warehouse=configuration.warehouse,
                database=database,
                schema=schema,
                role=configuration.role,
                autocommit=True
            ))
        else:
            engine = sqlalchemy.create_engine(URL(
                account=configuration.account,
                user=configuration.username,
                password=configuration.password,
                warehouse=configuration.warehouse,
                database=configuration.database,
                schema=configuration.schema,
            ))
    except Exception as e:
        logger.error("Caught an error. More Details : "+str(e))
    finally:
        return engine`

Hope this helps :-D

**Comment by jayend-manika** [comment] 2020-04-21 20:45
The issue happens for me on Python version 3.7.6. Pyarrow 0.17.0 and snowflakes-connector-python 2.2.4. If I downgrade it to version snowflakes-connector-python==2.2.2 and Pyarrow=0.16.0 I do not face the problem

**Comment by keller00** [comment] 2020-04-22 01:59
@jayend-manika we only support, pyarrow `0.16.0`, please install that with the most up to date connector. When you install the connector `pip` should tell you that we only support `0.16.0`.

**Comment by nickfielding** [comment] 2020-04-29 07:27
This issue also happens for me using Python 3.8.1 on Windows Server 2016.

**Comment by mckeown12** [comment] 2020-08-04 17:46
@keller00 Is this issue solved with `pyarrow 0.16.0`?  I'm using `snowflake-connector-python 2.2.10` and it seems to require  `pyarrow<0.18.0,>=0.17.0`.  With `0.17.0` I get 
```  
File "/usr/local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 733, in fetch_pandas_all
    raise NotSupportedError
snowflake.connector.errors.NotSupportedError: Unknown error
```

**Comment by chetansurwade** [comment] 2020-08-04 18:05
@keller00 I don't think the issue is addressed yet. And you are using a build which was released 17 hours ago at the time i'm writing this comment. check with an older release once.

**Comment by sfc-gh-mkeller** [comment] 2020-08-04 18:54
@mckeown12 we have since updated to `0.17`. The connector should now check during run time and warn you if you had the wrong version of `pyarrow` installed too.

@chetansurwade this isn't one specific issue. It could be caused by a bunch of different things, it might also be because of your server side settings. I just did a test with a brand new docker image: `docker run -it python:3.6 /bin/bash`, here is my code that worked for me:
Setup with:
```
apt update
apt install vim
pip install "snowflake-connector-python[pandas]"
```
```
import snowflake.connector 
import pandas as pd 
 
ctx = snowflake.connector.connect(...) 
 
# Create a cursor object. 
cur = ctx.cursor() 
 
# Execute a statement that will generate a result set. 
sql = "select randstr(abs(mod(random(), 100)), random()) from table(generator(rowcount => 10));" 
cur.execute(sql) 
 
df = cur.fetch_pandas_all() 
print(df.head())
```

Please reach out to Snowflake support so that we can help you better!

**Comment by sfc-gh-mkeller** [comment] 2020-11-23 22:25
This issue has been resolved in the last release. Python 3.8 built for Windows have been released.
Please reopen this ticket if it doesn't work for some reason and then we can take another look!

**Closed by sfc-gh-mkeller** 2020-11-23 22:25 UTC

**Comment by hjvouch** [comment] 2022-02-17 03:09
I am facing this issue on the following Windows setup

Python - 3.9.7
Pandas - 1.2.5
Pyarrow - 6.0.1
Snowflake Connector - 2.7.4

**Comment by pmateosmasa1** [comment] 2022-03-21 11:54
@hjvouch I had the same issue and I downgraded the Pyarrow dependency to 6.0.0 and it works
