### ISSUE TITLE
SNOW-699262: SFDictFileCache infinite loop

### ISSUE THREAD

**Issue by damonallison** [snowflakedb/snowflake-connector-python#1346] opened 2022-11-23 16:43 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0]

2. What operating system and processor architecture are you using?

Linux-5.4.202+-x86_64-with-glibc2.31

3. What are the component versions in the environment (`pip freeze`)?

absl-py==1.0.0
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
alembic @ file:///home/conda/feedstock_root/build_artifacts/alembic_1647367721563/work
altair @ file:///home/conda/feedstock_root/build_artifacts/altair_1640799865332/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1641898043316/work/dist
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1649500321618/work
asn1crypto==1.5.1
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1618968359944/work
astunparse==1.6.3
async-generator==1.10
async-timeout==4.0.2
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1640799537051/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backoff==2.2.1
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1649463573192/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1649361991009/work
blinker==1.4
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1637615122801/work
boto3==1.21.20
botocore==1.24.38
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1649629659164/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1648854164373/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==5.0.0
certifi==2021.10.8
certipy==0.1.3
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1636046055389/work
chardet==4.0.0
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1644853463426/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1648793473567/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1631273254894/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
comet-ml==3.28.3
conda==4.12.0
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1649385069444/work
configobj==5.0.6
confluent-kafka==1.9.2
cramjam==2.5.0
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1649035236822/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1648737828186/work
cytoolz==0.11.2
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1648827921498/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1649586347330/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
dill @ file:///home/conda/feedstock_root/build_artifacts/dill_1623610058511/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1648835875604/work
dulwich==0.20.35
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
everett==3.0.0
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1646044401614/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1641751198313/work/dist
fastparquet==0.8.1
fidelius @ git+https://github.com/shipt/beaker.git@e155ea1834f8a88f2f9044e177430e8989e1425c#subdirectory=fidelius
filelock==3.8.0
findspark @ file:///home/conda/feedstock_root/build_artifacts/findspark_1644599740637/work
flatbuffers==2.0
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1645629044586/work/source/flit_core
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1649448458275/work
frozenlist==1.3.0
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1648820545323/work
future==0.18.2
gast==0.5.3
gcloud-aio-auth==4.0.1
gcloud-aio-storage==7.0.1
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1641732907770/work
google-api-core==2.10.2
google-auth==2.6.3
google-auth-oauthlib==0.4.6
google-cloud-core==2.3.2
google-cloud-storage==2.6.0
google-crc32c==1.5.0
google-pasta==0.2.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1648882382645/work
grpcio==1.44.0
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1637963928098/work
HeapDict==1.0.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1642433548627/work
imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1649435053162/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1646036686179/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1648728288044/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1648277295813/work
inflection==0.5.1
install==1.3.5
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1649078348655/work/dist/ipykernel-6.12.0-py3-none-any.whl
ipympl @ file:///home/conda/feedstock_root/build_artifacts/ipympl_1645174282670/work
ipyparallel @ file:///home/conda/feedstock_root/build_artifacts/ipyparallel_1648846588293/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1648413562175/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1647456365981/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1649067096717/work
Jinja2==3.1.2
jmespath==0.10.0
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1633637554808/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1642000296051/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1649340884673/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1645024267147/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1648720900375/work
jupyter-telemetry @ file:///home/conda/feedstock_root/build_artifacts/jupyter_telemetry_1605173804246/work
jupyterhub @ file:///home/conda/feedstock_root/build_artifacts/jupyterhub-feedstock_1649252788048/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1649339215476/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649431904336/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1648484152099/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1647446862951/work
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1648854392795/work
libclang==13.0.0
libmambapy @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1649138401179/work/libmambapy
llvmlite==0.38.0
locket==0.2.0
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1649094500002/work
Mako @ file:///home/conda/feedstock_root/build_artifacts/mako_1649097013621/work
mamba @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1649138401179/work/mamba
Markdown==3.3.6
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1648737556467/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1639359646028/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
metakernel @ file:///home/conda/feedstock_root/build_artifacts/metakernel_1648594625035/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1635844679781/work
more-itertools==8.12.0
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1612895720168/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1648745988851/work
multidict==6.0.2
munkres==1.1.4
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1647450696711/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1646999386773/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1648822144012/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1649105480291/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1648959695634/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1649567584534/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1647377876077/work
notebook-shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1646330736330/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1644003844419/work
numexpr @ file:///home/conda/feedstock_root/build_artifacts/numexpr_1649636757217/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1649585247321/work
nvidia-ml-py3==7.352.0
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1643507977997/work
opt-einsum==3.3.0
orjson==3.8.2
oscrypto==1.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pamela==1.0.0
pandas==1.4.2
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1617910651905/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1632667180946/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1648857113814/work
portalocker @ file:///home/conda/feedstock_root/build_artifacts/portalocker_1645465641398/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1649447152425/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1649130487073/work
protobuf==4.21.9
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1648872973590/work
psycopg2==2.9.3
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1649384802055/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pycryptodomex==3.14.1
pycurl==7.45.1
pydantic==1.10.2
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1641580240686/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1638819640841/work
pyOpenSSL==21.0.0
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1649603503565/work
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1649013355209/work
pyshipt==3.0.0
pyshipt-cloud==1.0.1
pyshipt-experiments==2.9.0
pyshipt-logging==0.6.0
pyshipt-sql==1.2.5
pyshipt-streams==3.1.4
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1648857263093/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-dotenv==0.19.2
python-json-logger==2.0.2
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1647961439546/work
PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1649616400802/work
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1649055645150/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1641580202195/work
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rollbar==0.16.2
rsa==4.8
ruamel-yaml-conda @ file:///home/conda/feedstock_root/build_artifacts/ruamel_yaml_1636009144459/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1649033202141/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1649013070954/work
s3transfer==0.5.2
scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1645196657675/work
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1640464150285/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1644357253444/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1629095986539/work
semantic-version==2.9.0
semver==2.13.0
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
slackclient==2.9.3
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1648819188507/work
snowflake-connector-python==2.8.2
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1638550740809/work
spylon==0.3.0
spylon-kernel==0.4.1
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1649278569861/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1644872665635/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1644535581977/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1647802532210/work
tables @ file:///home/conda/feedstock_root/build_artifacts/pytables_1643135938562/work
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tenacity==8.1.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-cpu==2.8.0
tensorflow-io-gcs-filesystem==0.24.0
termcolor==1.1.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1649103779998/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1645693042223/work
tf-estimator-nightly==2.8.0.dev2021122109
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1649447161969/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1636177962100/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1648827245914/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1649051611147/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1635260543454/work
typing_extensions==4.4.0
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1649111919389/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1647489083693/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1648562593984/work
Werkzeug==2.1.1
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1647446890517/work
wrapt==1.14.0
wurlitzer==3.0.2
xlrd @ file:///home/conda/feedstock_root/build_artifacts/xlrd_1610224409810/work
yarl==1.7.2
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1645832288898/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1649012893348/work

4. What did you do?

I updated my version of `snowflake-python-connector` and tried to connect to Snowflake w/ and w/o Okta credentials.

5. What did you expect to see?

The connection attempt succeed

6. Can you set logging to DEBUG and collect the logs?

I don't have the machine logs, nor can I reproduce the issue after I cleaned the cache. I was however able to identify the stack which highlights the infinite loop.

```
Exception ignored in: <function SFDictFileCache.__del__ at 0x7f9f21d61280>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 541, in _load_if_should
    if self._should_load():
  File "/opt/conda/lib/python3.9/site-packages/snowflake/connector/cache.py", line 558, in _should_load
    if os.path.exists(self.file_path) and os.path.isfile(self.file_path):
  File "/opt/conda/lib/python3.9/genericpath.py", line 30, in isfile
    st = os.stat(path)
KeyboardInterrupt: 
```

**Comment by sfc-gh-aling** [comment] 2022-11-23 17:35
thanks for reaching out and sharing us with the stack, we're aware of the issue: https://github.com/snowflakedb/snowflake-connector-python/issues/1342 and currently investigating, we will do a bug fix release after fixing the issue.

btw, after cleaning up the cache, will the issue happen again some time in a future time or it's gone completely?

**Comment by damonallison** [comment] 2022-11-23 18:01
hey @sfc-gh-aling - after wiping the cache it's gone completely. this may be related to upgrading from a previous version of the connector (`2.7.6`) to the latest (`2.8.2`). The connector was previously working fine under `2.7.6` and started crashing on `2.8.2`.

**Comment by sfc-gh-aling** [comment] 2022-11-23 22:09
we've found the root cause, it's a bug in our code that when there're expired entries in the OCSP cache dict, the code will try to clean up the expired ones, and then reload. However, reload again kicks off the cleaning up procedure, leading to infinite recursion.

I had a PR out for fix the issue: https://github.com/snowflakedb/snowflake-connector-python/pull/1348

really appreciate sharing us with the error stack which helps us to locate the issue easily.
We plan to do a bug fix release very soon. for now please downgrade to the older version.

**Comment by shacker** [comment] 2022-11-28 22:06
I am also blocked by this. Happy to clear cache... but where? I don't see any snowflake keys in my redis cache, and I don't see a cache-related dir in the lib's dirs. I did delete all of the `pycache` dirs there but that didn't help.

**Comment by sfc-gh-aling** [comment] 2022-11-28 22:13
the paths to the cache are defined here: https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/ocsp_snowflake.py#L83-L99

apologize for the inconvenience and we will do a bug fix release today.

**Comment by shacker** [comment] 2022-11-28 22:16
@sfc-gh-aling Just posted my own update above as you were typing. Thanks!

**Comment by tekumara** [comment] 2022-11-28 23:22
For now, running this on an ubuntu machine resolved this for me:
```
rm ~/.cache/snowflake/ocsp_response_cache.json ~/.cache/snowflake/ocsp_response_validation_cache
```

Looking forward to the fix!

**Comment by sfc-gh-aling** [comment] 2022-11-29 01:26
hi folks, appreciate your understanding and patience.
we have just released v2.8.3 and yanked v2.8.2. please upgrade via command `pip install snowflake-connector-python --upgrade`.

please let me know if you still encounter the issue or need any other help.

**Comment by iamontheinet** [comment] 2022-12-13 00:13
Can we close this issue?

**Closed** 2022-12-13 00:36 UTC
Labels: bug, needs triage

**Comment by damonallison** [comment] 2022-12-13 00:37
We have not seen the issue in 2.8.3. Thank you for getting this resolved and pushed out so quickly!
