### ISSUE TITLE
AWS lambda docker container cannot resolve dependencies

### ISSUE THREAD

**Issue by AntonJansen** [snowflakedb/snowflake-connector-python#252] opened 2019-12-20 11:18 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.7.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic

3. What are the component versions in the environment (`pip list`)? 
Package                    Version   
-------------------------- ----------
asn1crypto                 1.2.0     
awscli                     1.16.306  
azure-common               1.1.24    
azure-storage-blob         2.1.0     
azure-storage-common       2.1.0     
boto3                      1.10.43   
botocore                   1.13.43   
certifi                    2019.11.28
cffi                       1.13.2    
chardet                    3.0.4     
colorama                   0.4.1     
cryptography               2.8       
docutils                   0.15.2    
future                     0.18.2    
idna                       2.8       
ijson                      2.5.1     
jmespath                   0.9.4     
numpy                      1.17.4    
oscrypto                   1.1.0     
pandas                     0.25.3    
pip                        19.3.1    
pyasn1                     0.4.8     
pycparser                  2.19      
pycryptodomex              3.9.4     
PyJWT                      1.7.1     
pyOpenSSL                  19.1.0    
python-dateutil            2.8.0     
pytz                       2019.3    
PyYAML                     5.1.2     
requests                   2.22.0    
rsa                        3.4.2     
s3transfer                 0.2.1     
setuptools                 41.6.0    
six                        1.13.0    
snowflake-connector-python 2.1.2     
snowflake-sqlalchemy       1.1.17    
SQLAlchemy                 1.3.12    
urllib3                    1.25.7    
wheel                      0.33.6 

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Used AWS SAM v0.38.0, added snowflake-connector-python to helloworld sam example's requirements.txt file.

Try to build the example in an AWS lambda container with
sam build -u

5. What did you expect to see?
Build succeeded

6. What did you see instead?
anton@anton-Virtual-Machine:~/aws/samexample/sam-app$ sam build -u
Starting Build inside a container
Building resource 'HelloWorldFunction'

Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting /home/anton/aws/samexample/sam-app/hello_world as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.1.2(wheel)}

7. Can you set logging to DEBUG and collect the logs?
With sam build debug:

anton@anton-Virtual-Machine:~/aws/samexample/sam-app$ sam build -u --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
Building resource 'HelloWorldFunction'

Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting /home/anton/aws/samexample/sam-app/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {docutils==0.15.2(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), chardet==3.0.4(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), pycryptodomex==3.9.4(wheel), python-dateutil==2.8.1(wheel), s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), cryptography==2.8(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), sqlalchemy==1.3.12(sdist), pyopenssl==19.1.0(wheel), pycparser==2.19(sdist), snowflake-connector-python==2.1.2(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), future==0.18.2(sdist), numpy==1.17.4(wheel), pyjwt==1.7.1(wheel)}
initial compatible: {docutils==0.15.2(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), chardet==3.0.4(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), pycryptodomex==3.9.4(wheel), python-dateutil==2.8.1(wheel), s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), pyopenssl==19.1.0(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), numpy==1.17.4(wheel), pyjwt==1.7.1(wheel)}
initial incompatible: {cryptography==2.8(wheel), future==0.18.2(sdist), snowflake-connector-python==2.1.2(wheel), pycparser==2.19(sdist), sqlalchemy==1.3.12(sdist)}
Downloading missing wheels: {cryptography==2.8(wheel), future==0.18.2(sdist), snowflake-connector-python==2.1.2(wheel), pycparser==2.19(sdist), sqlalchemy==1.3.12(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch cryptography==2.8
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch future==0.18.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch snowflake-connector-python==2.1.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch pycparser==2.19
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch sqlalchemy==1.3.12
compatible wheels after second download pass: {docutils==0.15.2(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), chardet==3.0.4(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), pycryptodomex==3.9.4(wheel), python-dateutil==2.8.1(wheel), s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), cryptography==2.8(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), pyopenssl==19.1.0(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), numpy==1.17.4(wheel), pyjwt==1.7.1(wheel)}
Build missing wheels from sdists (C compiling True): {pycparser==2.19(sdist), future==0.18.2(sdist), sqlalchemy==1.3.12(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/pycparser-2.19.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/future-0.18.2.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/SQLAlchemy-1.3.12.tar.gz
compatible after building wheels (no C compiling): {docutils==0.15.2(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), chardet==3.0.4(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), pycryptodomex==3.9.4(wheel), python-dateutil==2.8.1(wheel), s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), cryptography==2.8(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), sqlalchemy==1.3.12(wheel), pyopenssl==19.1.0(wheel), pycparser==2.19(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), future==0.18.2(wheel), numpy==1.17.4(wheel), pyjwt==1.7.1(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {docutils==0.15.2(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), chardet==3.0.4(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), pycryptodomex==3.9.4(wheel), python-dateutil==2.8.1(wheel), s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), cryptography==2.8(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), sqlalchemy==1.3.12(wheel), pyopenssl==19.1.0(wheel), pycparser==2.19(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), future==0.18.2(wheel), numpy==1.17.4(wheel), pyjwt==1.7.1(wheel)}
Final compatible: {s3transfer==0.2.1(wheel), certifi==2019.11.28(wheel), cryptography==2.8(wheel), docutils==0.15.2(wheel), asn1crypto==1.2.0(wheel), pytz==2019.3(wheel), six==1.13.0(wheel), azure-storage-common==2.1.0(wheel), oscrypto==1.1.0(wheel), sqlalchemy==1.3.12(wheel), pyopenssl==19.1.0(wheel), pandas==0.25.3(wheel), cffi==1.13.2(wheel), pycparser==2.19(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), ijson==2.5.1(wheel), azure-common==1.1.24(wheel), botocore==1.13.43(wheel), jmespath==0.9.4(wheel), idna==2.8(wheel), boto3==1.10.43(wheel), requests==2.22.0(wheel), urllib3==1.25.7(wheel), future==0.18.2(wheel), pycryptodomex==3.9.4(wheel), numpy==1.17.4(wheel), python-dateutil==2.8.1(wheel), pyjwt==1.7.1(wheel)}
Final incompatible: {snowflake-connector-python==2.1.2(wheel), cryptography==2.8(wheel)}
Final missing wheels: {snowflake-connector-python==2.1.2(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    requirements_path=self.manifest_path
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 144, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 213, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {snowflake-connector-python==2.1.2(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {snowflake-connector-python==2.1.2(wheel)}
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    requirements_path=self.manifest_path
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 144, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 213, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {snowflake-connector-python==2.1.2(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {snowflake-connector-python==2.1.2(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/__main__.py", line 137, in main
    mode=params.get('mode', None))
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 65, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 257, in run
    reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.1.2(wheel)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.1.2(wheel)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 21152, 'exitReason': 'UserException', 'exitCode': 1, 'requestId': 'bb66e213-3d85-4511-b884-ded8314d29de', 'installationId': '9b0b03dd-3c68-43c9-bf8b-4e7849972b58', 'sessionId': 'b2d3b269-c57d-44e6-ac70-f83bc815c1ef', 'executionEnvironment': 'CLI', 'pyversion': '3.7.5', 'samcliVersion': '0.38.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.1.2(wheel)}

----
It seems there is misconfiguration of the wheels dependencies breaking the pip resolver in the AWS lambda docker container.

**Comment by AntonJansen** [comment] 2019-12-23 10:21
Trying to build the snowflake connector in a AWS Lambda container seems to reveal the library conflict:
ERROR: aws-sam-cli 0.38.0 has requirement python-dateutil<2.8.1,~=2.6, but you'll have python-dateutil 2.8.1 which is incompatible.

**Comment by snowstakeda** [comment] 2020-01-08 22:24
I don't think the snowflake connector pins `python-dateutil`. Looks like `botocore` does but has decent range of support:
```
- python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1] 
```
Can you pin `python-dateutil` by your application?

**Comment by AntonJansen** [comment] 2020-01-19 13:32
I will try coming week and let you know the results.

**Comment by viller86** [comment] 2020-03-02 20:51
I have the same issue.

I use AWS SAM CLI 0.43.0

`Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), docutils==0.15.2(wheel), cffi==1.13.2(wheel), pyjwt==1.7.1(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), pycparser==2.19(sdist), snowflake-connector-python==2.2.1(wheel), jmespath==0.9.5(wheel), certifi==2019.11.28(wheel), s3transfer==0.3.3(wheel), urllib3==1.25.8(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), cryptography==2.8(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), idna==2.9(wheel), requests==2.23.0(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel)}
initial compatible: {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), docutils==0.15.2(wheel), cffi==1.13.2(wheel), pyjwt==1.7.1(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), jmespath==0.9.5(wheel), s3transfer==0.3.3(wheel), certifi==2019.11.28(wheel), urllib3==1.25.8(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), idna==2.9(wheel), requests==2.23.0(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel)}
initial incompatible: {cryptography==2.8(wheel), pycparser==2.19(sdist), snowflake-connector-python==2.2.1(wheel)}
Downloading missing wheels: {cryptography==2.8(wheel), pycparser==2.19(sdist), snowflake-connector-python==2.2.1(wheel)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch cryptography==2.8
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch pycparser==2.19
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch snowflake-connector-python==2.2.1
compatible wheels after second download pass: {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), docutils==0.15.2(wheel), cffi==1.13.2(wheel), pyjwt==1.7.1(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), jmespath==0.9.5(wheel), certifi==2019.11.28(wheel), s3transfer==0.3.3(wheel), urllib3==1.25.8(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), cryptography==2.8(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), idna==2.9(wheel), requests==2.23.0(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel)}
Build missing wheels from sdists (C compiling True): {pycparser==2.19(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/pycparser-2.19.tar.gz
compatible after building wheels (no C compiling): {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), docutils==0.15.2(wheel), cffi==1.13.2(wheel), pyjwt==1.7.1(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), pycparser==2.19(wheel), jmespath==0.9.5(wheel), certifi==2019.11.28(wheel), s3transfer==0.3.3(wheel), urllib3==1.25.8(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), cryptography==2.8(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), idna==2.9(wheel), requests==2.23.0(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), docutils==0.15.2(wheel), cffi==1.13.2(wheel), pyjwt==1.7.1(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), pycparser==2.19(wheel), jmespath==0.9.5(wheel), certifi==2019.11.28(wheel), s3transfer==0.3.3(wheel), urllib3==1.25.8(wheel), chardet==3.0.4(wheel), azure-storage-blob==2.1.0(wheel), cryptography==2.8(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), idna==2.9(wheel), requests==2.23.0(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel)}
Final compatible: {boto3==1.11.17(wheel), pycryptodomex==3.9.7(wheel), asn1crypto==1.3.0(wheel), urllib3==1.25.8(wheel), s3transfer==0.3.3(wheel), chardet==3.0.4(wheel), docutils==0.15.2(wheel), azure-storage-blob==2.1.0(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), pyopenssl==19.1.0(wheel), python-dateutil==2.8.1(wheel), pyjwt==1.7.1(wheel), pytz==2019.3(wheel), azure-storage-common==2.1.0(wheel), botocore==1.14.17(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), pycparser==2.19(wheel), idna==2.9(wheel), requests==2.23.0(wheel), jmespath==0.9.5(wheel), ijson==2.6.1(wheel), azure-common==1.1.24(wheel), certifi==2019.11.28(wheel)}
Final incompatible: {cryptography==2.8(wheel), snowflake-connector-python==2.2.1(wheel)}
Final missing wheels: {snowflake-connector-python==2.2.1(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {snowflake-connector-python==2.2.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {snowflake-connector-python==2.2.1(wheel)}
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {snowflake-connector-python==2.2.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {snowflake-connector-python==2.2.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.2.1(wheel)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.2.1(wheel)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 64424, 'exitReason': 'BuildError', 'exitCode': 1, 'requestId': '39de423d-0d7a-4216-a566-9b40c63d7ed3', 'installationId': '5307e530-1314-4c2b-9def-5ed27837e418', 'sessionId': '80bb4bd7-0eb1-4b1b-bec3-29e241cf872a', 'executionEnvironment': 'CLI', 'pyversion': '3.7.3', 'samcliVersion': '0.43.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.2.1(wheel)}
`

**Comment by keller00** [comment] 2020-03-02 20:59
Note that we release our python connector for `manylinux_2010` and AWS Lambda is still only on `manylinux1` and it only let's you install wheels for that platform.
For now we don't support AWS lambda.

**Comment by keller00** [comment] 2020-03-02 21:51
My bad, I don't really know how AWS Lambda works. 😅

So we DO support AWS Lambda, but the issue you are currently seeing is caused by  https://github.com/awslabs/aws-lambda-builders
It allows only wheels files built for `manylinux1` as I said, but we build for `manylinux2010`.

**Comment by mikenac** [comment] 2020-03-09 13:27
@keller00 is there a way to work around this? We are jammed up in a spot where we need the newer version of the library, but not it does not support Lambda.

**Comment by viller86** [comment] 2020-03-09 19:24
@mikenac

**Comment by keller00** [comment] 2020-03-09 20:20
You can find our tried and tested requirements files here: https://github.com/snowflakedb/snowflake-connector-python/tree/master/tested_requirements

**Comment by keller00** [comment] 2020-03-12 23:06
https://github.com/snowflakedb/snowflake-connector-python/issues/287#issuecomment-598470501

**Comment by viller86** [comment] 2020-04-16 18:26
Hey @keller00, when the release is scheduled?

**Comment by sfc-gh-mkeller** [comment] 2020-04-17 00:54
@viller86 FYI I went through an account change
It was released I think 2 weeks ago.
https://pypi.org/project/snowflake-connector-python/#files now has `manylinux1` wheels.
Could someone verify for me that this new release works with the python builder?

**Comment by viller86** [comment] 2020-04-17 18:17
@sfc-gh-mkeller, thanks I will test it today

**Comment by viller86** [comment] 2020-04-22 18:58
It is working now

**Comment by sfc-gh-mkeller** [comment] 2020-04-22 21:05
Great, thanks @viller86 ! 🎊 
Going to close this issue until someone has any more issue with this.

**Closed by sfc-gh-mkeller** 2020-04-22 21:05 UTC
Labels: question

**Comment by valentin-martinez-gama** [comment] 2022-06-22 20:25
Hey I am having this SAM Build error again with Python 3.9 and snowflake-connector-python==2.7.8
