### ISSUE TITLE
SNOW-186747: Release 2.3.0 breaks requests for other modules

### ISSUE THREAD

**Issue by dodijk** [snowflakedb/snowflake-connector-python#377] opened 2020-08-25 09:36 UTC
In upgrading to the latest release of the Snowflake Python connector, we have seen that using the requests library from other 
modules is broken. I think this is caused by the [monkey patching `urllib3` with `ssl_wrap_socket_with_ocsp`](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/ssl_wrap_socket.py#L74) and the [removal of a default value for `FEATURE_OCSP_MODE`](https://github.com/snowflakedb/snowflake-connector-python/commit/83dfe771c5404657f2008fec15bf0386185b6d70#diff-a8cb7f98804ae57600a6efa12d4b50dfL17). 

1. What version of Python are you using (`python --version`)?
Python 3.7.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Darwin-19.6.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)?
```
snowflake-connector-python     2.3.0`
requests                       2.24.0
requests-oauthlib              1.3.0
```
Partial list, I can add more where relevant.

4. What did you do?
I created a minimal example:
```
import snowflake.connector
import requests

requests.post('https://postman-echo.com')
```

5. What did you expect to see?
```
<Response [404]>
```

6. What did you see instead?
```
NameError: name 'FEATURE_OCSP_MODE' is not defined
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```
```
>>> import snowflake.connector
2020-08-25 11:23:12,973 - MainThread ssl_wrap_socket.py:73 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
2020-08-25 11:23:12,975 - MainThread auth.py:47 - <module>() - DEBUG - Failed to import keyring module. err=[No module named 'keyring']
2020-08-25 11:23:12,975 - MainThread auth.py:67 - <module>() - DEBUG - cache directory: /Users/dodijk/Library/Caches/Snowflake
/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/snowflake/connector/options.py:40: UserWarning: You have an incompatible version of 'pyarrow' installed, please install a version that adheres to: 'pyarrow<0.18.0,>=0.17.0; extra == "pandas"'
  warn_incompatible_dep('pyarrow', _installed_pyarrow.version, _expected_version)
>>> import requests
>>> requests.post('https://postman-echo.com')
2020-08-25 11:23:30,340 - MainThread ocsp_snowflake.py:364 - reset_cache_dir() - DEBUG - cache directory: /Users/dodijk/Library/Caches/Snowflake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Users/dodijk/.pyenv/versions/3.7.5/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_socket.py", line 386, in ssl_wrap_socket_with_ocsp
    FEATURE_OCSP_MODE.name,
NameError: name 'FEATURE_OCSP_MODE' is not defined
```

**Comment by alex-bizjedi** [comment] 2020-08-25 10:06
Experience the same issue

**Comment by sfc-gh-mkeller** [comment] 2020-08-25 16:17
Hi,

> I think this is caused by the [monkey patching `urllib3` with `ssl_wrap_socket_with_ocsp`](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/ssl_wrap_socket.py?rgh-link-date=2020-08-25T09%3A36%3A21Z#L74) and the [removal of a default value for `FEATURE_OCSP_MODE`](https://github.com/snowflakedb/snowflake-connector-python/commit/83dfe771c5404657f2008fec15bf0386185b6d70#diff-a8cb7f98804ae57600a6efa12d4b50dfL17).

The issue is caused by a removed constant.
It was fixed in #376 and we will be releasing 2.3.1 soon with the fix, if a fix is necessary earlier please downgrade to 2.2.10.

Also @dodijk we don't support requests 2.24.0 and that will break things, please downgrade it by one version.

**Comment by sfc-gh-mkeller** [comment] 2020-08-26 04:37
We have released 2.3.1 a few hours ago, please let us know if this is not working!

**Comment by arterrey** [comment] 2020-08-26 07:13
Also experiencing this issue.

**Comment by alex-bizjedi** [comment] 2020-08-26 08:14
The fix worked. Everything is fine now.

**Comment by dodijk** [comment] 2020-08-26 18:06
I can confirm this fix works for me too. Thanks for the quick patch, @sfc-gh-mkeller! Issue can be closed as far as I am concerned.

**Closed** 2020-08-26 19:08 UTC
