### ISSUE TITLE
SNOW-995297: Externalbrowser auth mode without a local browser

### ISSUE THREAD

**Issue by dougbyrne** [snowflakedb/snowflake-connector-python#1837] opened 2023-12-20 16:32 UTC
### What is the current behavior?

The externalbrowser auth mode will attempt to open a browser, and will fall back to asking the user to copy and paste a url into a browser. However, this fallback doesn't always trigger in remote, virtual, or containerized environments.

### What is the desired behavior?

Provide a method to force the fallback to be used. Either an additional auth mode, or an environment variable, to force the client to use this method.

### How would this improve `snowflake-connector-python`?

Externalbrowser auth would be more useful for remote, virtual, and containerized environments.

### References and other background

https://github.com/snowflakedb/snowflake-connector-python/blob/2851d3bb9578cb3082172ff9ec708e52c2c7692c/src/snowflake/connector/auth/webbrowser.py#L162-L167

**Comment by sfc-gh-dszmolka** [comment] 2024-03-11 11:31
this looks like a duplicate of https://github.com/snowflakedb/snowflake-connector-python/issues/1637

if i'm incorrect and this is not a request looking for support for headless operation for externalbrowser auth, please comment with the details and I'll reopen. Thank you !

**Closed by sfc-gh-dszmolka** 2024-03-11 11:31 UTC
Labels: enhancement, feature, status-triage_done
