### ISSUE TITLE
Downloading snowflake-connector-python-2.3.10.tar.gz (324 kB)      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.5/324.5 kB 69.6 MB/s eta 0:00:00   Installing build dependencies: started   Installing build dependencies: still running...   Installing build dependencies: finished with status 'error'   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by omptech** [snowflakedb/snowflake-connector-python#1260] opened 2022-09-26 20:04 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.9

2. What operating system and processor architecture are you using?

   ubuntu-20.04 and 64 bit

**Comment by sfc-gh-achandrasekaran** [comment] 2022-09-26 20:13
Hi @omptech what is the issue exactly?

**Comment by sfc-gh-sfan** [comment] 2022-09-26 20:15
Hi @omptech can you post complete log lines?

**Comment by omptech** [comment] 2022-09-26 20:37
pip install snowflake-connector-python is not working in azure devops build pipeline

**Comment by sfc-gh-sfan** [comment] 2022-09-26 21:12
Can you provide more logs for the failure? I'm not sure I know the details of this "azure devops build pipeline" to provide help.

**Comment by al-cheb** [comment] 2022-09-28 10:40
This issue is not related to `snowflake-connector-python` pacakge , it's by design how pip works:
1. requirement.txt - https://github.com/actions/runner-images/files/9657507/requirement.txt
2. pip3 install -r requirement.txt
3. Failed logs:  [4_Run pip3 install -r requirements.txt.txt](https://github.com/snowflakedb/snowflake-connector-python/files/9664084/4_Run.pip3.install.-r.requirements.txt.txt)

```
Collecting snowflake-connector-python
  Downloading snowflake_connector_python-2.7.12-cp39-cp39-manylinux_2_17_x86_64.manylinux[201](https://github.com/roasted-eggplant/alcheb-test/actions/runs/3142779450/jobs/5106772737#step:4:202)4_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 101.2 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.11-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 94.5 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.9-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 113.7 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting snowflake-connector-python
  Downloading snowflake_connector_python-2.7.8-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 116.2 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.7-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 123.2 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.6-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 112.9 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 115.5 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 111.2 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.2-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 114.1 MB/s eta 0:00:00
  Downloading snowflake_connector_python-2.7.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 118.4 MB/s eta 0:00:00

```

**Comment by sfc-gh-aling** [comment] 2023-03-20 17:40
looks like you are working with an old version of the connector. it's trying to download the source distribution and build locally.
You can try install the latest connector which has binary distribution for most the of platform and does not require local building.

I'm closing the issue, feel free to reach out if you still encounter the issue.

**Closed by sfc-gh-aling** 2023-03-20 17:40 UTC
Labels: bug, triaged
