### ISSUE TITLE
SNOW-151669: Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_result

### ISSUE THREAD

**Issue by chetansurwade** [snowflakedb/snowflake-connector-python#296] opened 2020-04-09 07:25 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
A. 3.8.2 64 bit
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
A. Windows-10-10.0.18362-SP0
3. What are the component versions in the environment (`pip list`)? 
A. PFB
Package                       Version   
----------------------------- ----------
alabaster                     0.7.12
asn1crypto                    1.3.0
astroid                       2.3.3     
atomicwrites                  1.3.0
attrs                         19.3.0
autopep8                      1.5
azure-common                  1.1.25
azure-storage-blob            2.1.0
azure-storage-common          2.1.0
Babel                         2.8.0
boto3                         1.11.17
botocore                      1.14.17
certifi                       2019.11.28
cffi                          1.13.2    
chardet                       3.0.4
colorama                      0.4.3
cryptography                  2.8
docutils                      0.15.2
idna                          2.9       
ijson                         2.6.1
imagesize                     1.2.0
isort                         4.3.21
Jinja2                        2.11.1
jmespath                      0.9.5
keyring                       21.2.0
lazy-object-proxy             1.4.3
MarkupSafe                    1.1.1
mccabe                        0.6.1
more-itertools                8.2.0
numpy                         1.18.2
oscrypto                      1.2.0
packaging                     20.3
pandas                        1.0.3
pip                           20.0.2    
pluggy                        0.13.1
py                            1.8.1
pyarrow                       0.16.0    
pycodestyle                   2.5.0
pycparser                     2.20
pycryptodomex                 3.9.7
Pygments                      2.6.1
PyJWT                         1.7.1
pylint                        2.4.4
pyodbc                        4.0.30
pyOpenSSL                     19.1.0
pyparsing                     2.4.6
pytest                        5.4.1
python-dateutil               2.8.1
python-dotenv                 0.12.0
pytz                          2019.3
pywin32-ctypes                0.2.0
requests                      2.23.0
s3transfer                    0.3.3     
setuptools                    41.2.0
six                           1.14.0
snowballstemmer               2.0.0
snowflake-connector-python    2.2.3
snowflake-sqlalchemy          1.2.3
Sphinx                        2.4.4
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
SQLAlchemy                    1.3.15
sqlalchemy-access             1.0.3
static3                       0.7.0
urllib3                       1.25.8
wcwidth                       0.1.9
wrapt                         1.11.2
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A. Just use the connector as sqlalchemy engine.
5. What did you expect to see?
A. No import Errors
6. What did you see instead?
A. Import Errors, although in debug mode.
7. Can you set logging to DEBUG and collect the logs?
A. Already done that.
```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by keller00** [comment] 2020-04-09 17:51
Hi, this is a duplicate of #295 
Let's continue on that issue!

**Closed by keller00** 2020-04-09 17:51 UTC
