### ISSUE TITLE
SNOW-557144: Please update dependency requirements on pandas to allow 1.4 releases

### ISSUE THREAD

**Issue by mallman** [snowflakedb/snowflake-connector-python#1071] opened 2022-03-09 02:49 UTC
Please update dependency requirements on pandas to allow 1.4 releases, cf https://github.com/snowflakedb/snowflake-connector-python/pull/1036.

**Comment by mvashishtha** [comment] 2022-11-01 03:45
Duplicate of #1036

**Comment by sfc-gh-achandrasekaran** [comment] 2023-03-11 00:48
This has since been added

**Closed by sfc-gh-achandrasekaran** 2023-03-11 00:48 UTC
