### ISSUE TITLE
SNOW-172208: AttributeError: 'SSLSocket' object has no attribute 'connection' while running test on Airflow

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [snowflakedb/snowflake-connector-python#335] opened 2020-07-01 19:47 UTC
I found a similar issue at https://github.com/snowflakedb/snowflake-connector-python/issues/239 which was closed.

Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

`Python 3.7.8`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Linux-4.19.76-linuxkit-x86_64-with-debian-10.4`

3. What are the component versions in the environment (`pip list`)? 

```
Package                    Version
-------------------------- ---------
alembic                    1.4.2
amqp                       2.6.0
apache-airflow             1.10.10
apispec                    1.3.3
argcomplete                1.11.1
asn1crypto                 1.3.0
attrs                      19.3.0
azure-common               1.1.25
azure-core                 1.6.0
azure-storage-blob         12.3.2
Babel                      2.8.0
bcrypt                     3.1.7
billiard                   3.6.3.0
boto3                      1.13.26
botocore                   1.16.26
cached-property            1.5.1
cattrs                     0.9.2
celery                     4.4.6
certifi                    2020.6.20
cffi                       1.14.0
chardet                    3.0.4
click                      7.1.2
colorama                   0.4.3
colorlog                   4.0.2
configparser               3.5.3
croniter                   0.3.34
cryptography               2.9.2
datadog                    0.37.1
decorator                  4.4.2
defusedxml                 0.6.0
dill                       0.3.2
dnspython                  1.16.0
docutils                   0.15.2
email-validator            1.1.1
Flask                      1.1.2
Flask-Admin                1.5.4
Flask-AppBuilder           2.3.4
Flask-Babel                1.0.0
Flask-Caching              1.3.3
Flask-JWT-Extended         3.24.1
Flask-Login                0.4.1
Flask-OpenID               1.2.5
Flask-SQLAlchemy           2.4.3
flask-swagger              0.2.13
Flask-WTF                  0.14.3
flower                     0.9.4
funcsigs                   1.0.2
future                     0.18.2
graphviz                   0.14
gunicorn                   19.10.0
hmsclient                  0.1.1
humanize                   0.5.1
idna                       2.10
importlib-metadata         1.7.0
iso8601                    0.1.12
isodate                    0.6.0
itsdangerous               1.1.0
JayDeBeApi                 1.2.3
Jinja2                     2.10.3
jmespath                   0.10.0
JPype1                     0.7.1
json-merge-patch           0.2
jsonschema                 3.2.0
kombu                      4.6.11
lazy-object-proxy          1.5.0
lockfile                   0.12.2
Mako                       1.1.3
Markdown                   2.6.11
MarkupSafe                 1.1.1
marshmallow                2.21.0
marshmallow-enum           1.5.1
marshmallow-sqlalchemy     0.23.1
msrest                     0.6.17
mysqlclient                1.3.14
natsort                    7.0.1
ndg-httpsclient            0.5.1
numpy                      1.19.0
oauthlib                   3.1.0
oscrypto                   1.2.0
pandas                     0.25.3
paramiko                   2.7.1
pendulum                   1.4.4
pip                        20.1.1
prison                     0.1.3
psutil                     5.7.0
psycopg2-binary            2.8.5
pyasn1                     0.4.8
pycparser                  2.20
pycryptodomex              3.9.8
Pygments                   2.6.1
PyHive                     0.6.2
PyJWT                      1.7.1
PyNaCl                     1.4.0
pyOpenSSL                  19.1.0
pyrsistent                 0.16.0
pysftp                     0.2.9
python-daemon              2.1.2
python-dateutil            2.8.1
python-editor              1.0.4
python3-openid             3.2.0
pytz                       2020.1
pytzdata                   2019.3
PyYAML                     5.3.1
redis                      3.2.0
requests                   2.24.0
requests-oauthlib          1.3.0
s3transfer                 0.3.3
setproctitle               1.1.10
setuptools                 47.3.1
six                        1.15.0
snowflake-connector-python 2.2.8
snowflake-sqlalchemy       1.2.3
SQLAlchemy                 1.3.18
SQLAlchemy-JSONField       0.9.0
SQLAlchemy-Utils           0.36.6
sshtunnel                  0.1.5
tabulate                   0.8.7
tenacity                   4.12.0
termcolor                  1.1.0
text-unidecode             1.2
thrift                     0.13.0
tornado                    5.1.1
typing-extensions          3.7.4.2
tzlocal                    1.5.1
unicodecsv                 0.14.1
urllib3                    1.25.9
vine                       1.3.0
Werkzeug                   0.16.1
wheel                      0.34.2
WTForms                    2.3.1
zipp                       3.1.0
zope.deprecation           4.4.0
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I am trying to run an airflow DAG using the following example script:

```python
import logging

import airflow
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.contrib.hooks.snowflake_hook import SnowflakeHook
from airflow.contrib.operators.snowflake_operator import SnowflakeOperator

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

args = {"owner": "Airflow", "start_date": airflow.utils.dates.days_ago(2)}

dag = DAG(
    dag_id="snowflake_connector", default_args=args, schedule_interval=None
)

create_insert_query = [
    """create table public.test_table (amount number);""",
    """insert into public.test_table values(1),(2),(3);""",
]


def row_count(**context):
    dwh_hook = SnowflakeHook(snowflake_conn_id="snowflake")
    result = dwh_hook.get_first("select count(*) from public.test_table")
    logging.info("Number of rows in `public.test_table`  - %s", result[0])


with dag:
    create_insert = SnowflakeOperator(
        task_id="snowfalke_create",
        sql=create_insert_query,
        snowflake_conn_id="snowflake",
    )

    get_count = PythonOperator(task_id="get_count", python_callable=row_count)
create_insert >> get_count
```

5. What did you expect to see?

No errors.

6. What did you see instead?

```
[2020-07-01 19:09:35,882] {{logging_mixin.py:112}} INFO - [2020-07-01 19:09:35,882] {{connection.py:214}} INFO - Snowflake Connector for Python Version: 2.2.8, Python Version: 3.7.8, Platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.4
[2020-07-01 19:09:35,883] {{logging_mixin.py:112}} INFO - [2020-07-01 19:09:35,883] {{connection.py:725}} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2020-07-01 19:09:35,883] {{logging_mixin.py:112}} INFO - [2020-07-01 19:09:35,883] {{connection.py:741}} INFO - Setting use_openssl_only mode to False
[2020-07-01 19:11:40,595] {{logging_mixin.py:112}} INFO - [2020-07-01 19:11:40,594] {{network.py:641}} ERROR - 'SSLSocket' object has no attribute 'connection'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 762, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_socket.py", line 404, in ssl_wrap_socket_with_ocsp
    ).validate(server_hostname, ret.connection)
AttributeError: 'SSLSocket' object has no attribute 'connection'
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

```
[2020-07-01 19:41:23,116] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,116] {{connection.py:214}} INFO - Snowflake Connector for Python Version: 2.2.8, Python Version: 3.7.8, Platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.4
[2020-07-01 19:41:23,117] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,116] {{connection.py:412}} DEBUG - connect
[2020-07-01 19:41:23,117] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,117] {{connection.py:630}} DEBUG - __config
[2020-07-01 19:41:23,117] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,117] {{connection.py:725}} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2020-07-01 19:41:23,118] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,118] {{connection.py:741}} INFO - Setting use_openssl_only mode to False
[2020-07-01 19:41:23,119] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,119] {{converter.py:131}} DEBUG - use_numpy: False
[2020-07-01 19:41:23,120] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,119] {{connection.py:556}} DEBUG - REST API object was created: ***.snowflakecomputing.com:443
[2020-07-01 19:41:23,120] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,120] {{auth.py:137}} DEBUG - authenticate
[2020-07-01 19:41:23,121] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,121] {{auth.py:172}} DEBUG - assertion content: *********
[2020-07-01 19:41:23,121] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,121] {{auth.py:184}} DEBUG - account=***, user=***, database=DW, schema=, warehouse=TEST_WH, role=, request_id=da51ce31-e5af-418b-972d-c1656046045c
[2020-07-01 19:41:23,123] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,122] {{auth.py:210}} DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.2.8', 'SVN_REVISION': None, 'ACCOUNT_NAME': '***', 'LOGIN_NAME': '***', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Linux', 'OS_VERSION': 'Linux-4.19.76-linuxkit-x86_64-with-debian-10.4', 'PYTHON_VERSION': '3.7.8', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'GCC 8.3.0', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None, 'CLIENT_STORE_TEMPORARY_CREDENTIAL': None}, 'SESSION_PARAMETERS': {'CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY': 900, 'CLIENT_PREFETCH_THREADS': 4}}
[2020-07-01 19:41:23,124] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,124] {{network.py:896}} DEBUG - Active requests sessions: 1, idle: 0
[2020-07-01 19:41:23,125] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,124] {{network.py:593}} DEBUG - remaining request timeout: 120, retry cnt: 1
[2020-07-01 19:41:23,125] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,125] {{network.py:738}} DEBUG - socket timeout: 60
[2020-07-01 19:41:23,477] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,477] {{ocsp_snowflake.py:363}} DEBUG - cache directory: /usr/local/airflow/.cache/snowflake
[2020-07-01 19:41:23,546] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,545] {{ssl_wrap_socket.py:399}} DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
[2020-07-01 19:41:23,546] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,546] {{ocsp_snowflake.py:400}} DEBUG - ocsp_response_cache_uri: file:///usr/local/airflow/.cache/snowflake/ocsp_response_cache.json
[2020-07-01 19:41:23,547] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,546] {{ocsp_snowflake.py:402}} DEBUG - OCSP_VALIDATION_CACHE size: 0
[2020-07-01 19:41:23,547] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,547] {{ocsp_snowflake.py:202}} DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
[2020-07-01 19:41:23,548] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,547] {{ocsp_snowflake.py:236}} DEBUG - OCSP dynamic cache server RETRY URL: None
[2020-07-01 19:41:23,549] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,549] {{ocsp_snowflake.py:537}} DEBUG - Failed to check OCSP response cache file. No worry. It will validate with OCSP server: file: /usr/local/airflow/.cache/snowflake/ocsp_response_cache.json, lock directory: /usr/local/airflow/.cache/snowflake/ocsp_response_cache.json.lck, error: [Errno 2] No such file or directory: '/usr/local/airflow/.cache/snowflake/ocsp_response_cache.json'
[2020-07-01 19:41:23,550] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,549] {{ocsp_snowflake.py:439}} DEBUG - Failed to locate OCSP response cache file. No worry. It will validate with OCSP server: /usr/local/airflow/.cache/snowflake/ocsp_response_cache.json
[2020-07-01 19:41:23,553] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,551] {{network.py:854}} DEBUG - Hit retryable client error. Retrying... Ignore the following error stack: 'SSLSocket' object has no attribute 'connection'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 762, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_socket.py", line 404, in ssl_wrap_socket_with_ocsp
    ).validate(server_hostname, ret.connection)
AttributeError: 'SSLSocket' object has no attribute 'connection'
[2020-07-01 19:41:23,554] {{logging_mixin.py:112}} INFO - [2020-07-01 19:41:23,554] {{network.py:669}} DEBUG - retrying: errorclass=<class 'AttributeError'>, error='SSLSocket' object has no attribute 'connection', counter=1, sleeping=3(s)
```

EDIT:
I also got this down to a minimal test case running in the airflow environment:

```
Python 3.7.8 (default, Jun 30 2020, 18:36:05)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snowflake.connector
>>> ctx = snowflake.connector.connect(user='***', password='***', account='***')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 762, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_socket.py", line 404, in ssl_wrap_socket_with_ocsp
    ).validate(server_hostname, ret.connection)
AttributeError: 'SSLSocket' object has no attribute 'connection'
```

**Comment by vince5678** [comment] 2020-07-02 08:16
I had the same issue with `snowflake-ingest` and `snowflake-connector-python` , I solved it by forcing those package versions, note sure which one caused the problem
```
snowflake-ingest===1.0.2
snowflake-connector-python===2.2.7
boto3===1.13.25
botocore===1.16.25
certifi===2020.4.5.2
msrest===0.6.15
pycryptodomex===3.9.7
requests===2.23.0
```

**Comment by thomasdziedzic-pd** [comment] 2020-07-02 14:27
I solved it by setting the package version: `requests===2.23.0`

**Comment by sfc-gh-mkeller** [comment] 2020-07-02 21:26
Duplicate of #324 
Let me close this, please!

**Closed by sfc-gh-mkeller** 2020-07-02 21:26 UTC

**Comment by jasonminsookim** [comment] 2020-07-04 22:39
> I had the same issue with `snowflake-ingest` and `snowflake-connector-python` , I solved it by forcing those package versions, note sure which one caused the problem
> 
> ```
> snowflake-ingest===1.0.2
> snowflake-connector-python===2.2.7
> boto3===1.13.25
> botocore===1.16.25
> certifi===2020.4.5.2
> msrest===0.6.15
> pycryptodomex===3.9.7
> requests===2.23.0
> ```

I had to use this approach to get it to stop spitting out the attribute error. Even when I installed `requests===2.23.0`, I got the same error.

**Comment by yousefissa** [comment] 2020-10-02 17:28
Still getting the same error with `requests===2.23.0`

Anyone have any other solutions?

**Comment by okeeffdp** [comment] 2020-11-27 16:10
I received this error when I uninstalled requests and tried to reinstall it.

> snowflake-connector-python 2.3.5 requires requests<2.24.0, but you'll have requests 2.25.0 which is incompatible.

Luckily this worked for me.

```bash
pip install 'requests<2.24.0'
```
This command did the trick for me.

**Comment by alexanderpo-hrbl** [comment] 2020-12-22 03:40
Having the same problem. Downgrading requests isn't working for me though.

**Comment by okeeffdp** [comment] 2020-12-23 18:56
@alexanderpo-hrbl What error message did you get from pip or python?
